### ISSUE TITLE
Remote database

### ISSUE THREAD

**Issue by vladimir-yuldashev** [ForestAdmin/lumber#1]
I am trying to use remote database.

Credentials are correct.

````➜  lumber generate
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? ****
? What's the database hostname? *****
? What's the database port? 3306
? What's the database user?  remote
? What's the database password? [optional]  ****************
? Choose a project name:  lumber
error: 💀  Ouch, cannot connect to the database 💀

**Comment by eibrahim** [comment]
I have the same issue trying to connect to remote database on heroku

**Comment by SeyZ** [comment]
Hey @vladimir-yuldashev and @eibrahim !

Thanks for report! The version `1.0.3` fixes the issue and is available :) Can you upgrade the version of your lumber and try again?

`$ npm update -g lumber-cli`

Feel free to reopen the issue if you still have the problem.

**Comment by vladimir-yuldashev** [comment]
Now I get:

````(node:11416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'dbName' of undefined
(node:11416) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.````

**Comment by eibrahim** [comment]
worked for me once i added the --ssl flag.  thanks.

**Comment by vladimir-yuldashev** [comment]
@eibrahim It did not work for me.

**Comment by rosatof** [comment]
This is not working with remote DB for me neither, works only localhost.

`error: 💀  Ouch, cannot connect to the database 💀`

**Comment by rosatof** [comment]
@SeyZ current version is 1.0.1, can't find version 1.0.3, how did u get it?

**Comment by SeyZ** [comment]
Hey @rosatof here on NPM: https://www.npmjs.com/package/lumber-cli
You can upgrade using `[sudo] npm update -g lumber-cli`

**Comment by rosatof** [comment]
Hey @SeyZ , 
Thank you for your answer.
I did run `npm install/update -g lumber-cli` which installed lumber-cli@1.0.4.
But `lumber -V ` keep returning 1.0.1 and`lumber generate --ssl` leads to cannot connect DB message. 
My Credentials are valid since they are used by an other framework.

Any leads ?

**Comment by vladimir-yuldashev** [comment]
@rosatof `lumber -V` seems having an old information. It should be 1.0.4

**Comment by rosatof** [comment]
Any idea about the DB connection issue ?

**Comment by vladimir-yuldashev** [comment]
@rosatof Can you show you console output with hided passwords?

**Comment by SeyZ** [comment]
@rosatof Can you try to upgrade our lumber-cli with this command:
`npm install -g lumber-cli@latest` ?

Then `lumber --version` should respond with `1.0.4`. Then, I think your issue will be fixed.

**Comment by rosatof** [comment]
I tried with different version of node, same result...

▶ npm install -g lumber-cli@latest
/Users/rosatof/.nvm/versions/node/v6.2.0/bin/lumber -> /Users/rosatof/.nvm/versions/node/v6.2.0/lib/node_modules/lumber-cli/index.js
/Users/rosatof/.nvm/versions/node/v6.2.0/lib
└── lumber-cli@1.0.4 

~                                                                              
▶ lumber -V                       
1.0.1

~                                                                              
▶ lumber --version
1.0.1

**Comment by rosatof** [comment]
@SeyZ @vladimir-yuldashev 

Ok i think i got it! 
there is a ":" char in my DB password and it's conflicting with the DATABASE_URL format in the .env
`DATABASE_URL=mysql://root:password@localhost:3306/dbname`

BTW lumber -V keep returning 1.0.1

Thank you guys for your help!

**Comment by aldieemaulana** [comment]
I have same problem and I'm already update.

**Comment by SeyZ** [comment]
@aldieemaulana do you have `:` char in your user database or password database?

**Comment by aldieemaulana** [comment]
@SeyZ yes No, 

`sudo lumber generate --ssl
[sudo] password for aldieemaulana: 
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? lumberfirst
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]  *********
? Choose a project name:  lumberfirst
? What's your email address?  aldieemaulana@gmail.com
? Choose a password:  *********
error: 💀  Ouch, cannot connect to the database 💀
`

**Comment by aldieemaulana** [comment]
@vladimir-yuldashev It still same, still not work with same error.

**Comment by SeyZ** [comment]
@aldieemaulana You are using `--ssl` option but you specify `localhost` as the database hostname. Are you sure?
