### ISSUE TITLE
Exclude .DS_Store on macOS

### ISSUE THREAD

**Issue by oxplayru** [ForestAdmin/lumber#102]
If DS_Store exists in forest folder then loading fail with this error:

[forest] 🌳🌳🌳  Forest customization failed due to a syntax error: Unexpected token ILLEGAL in MY_PATH/.DS_Store:1

**Comment by chriseaton** [comment]
Probably would be good just to ignore dotfiles entirely.

**Comment by arnaudbesnier** [comment]
Hey @oxplayru,

Thanks for the report!

I think this issue is fixed now. You just have to upgrade the `forest-express-sequelize` (https://github.com/ForestAdmin/forest-express-sequelize) package of your project generated by Lumber.

Please re-open this issue if it is not fixed.

🌲🌲🌲
