### ISSUE TITLE
Custom responses not working when overriding admin actions

### ISSUE THREAD

**Issue by manurana** [ForestAdmin/lumber#103]
I am handling a PUT on a particular model with my own code. It does nothing but send back a custom response. The UI is receiving that response, but not displaying it.

Here is my code
```javascript
function updateCityVehicleType(req, res) {
  res.send({
    success: 'Please close this record as it has been deactivated'
  });
}

router.put('/city_vehicle_type/:id', liana.ensureAuthenticated, updateCityVehicleType);
```

If I inspect the network request, I can see that this is the response that is coming
`{"success":"Please close this record as it has been deactivated"}`

But the UI is not displaying it. It displays the default message.

**Comment by manurana** [comment]
Hi @arnaudbesnier : the documentation is here : https://doc.forestadmin.com/developer-guide/lumber.html#customizing-response

**Comment by manurana** [comment]
This is still not happening. Just checked again

**Comment by SeyZ** [comment]
It should now works. Here's the updated documentation: https://doc.forestadmin.com/developer-guide/lumber.html#customizing-response
Please reopen this issue if it still happens.
