### ISSUE TITLE
Any way to make login in a custom API?

### ISSUE THREAD

**Issue by arthurflor** [ForestAdmin/lumber#106]
Hey everyone!
My project consists make a admin panel and a app for insertion of the data. 
Well, the lumber/forest admin is amazing, but I have a doubt with the app login. Is there any way to make authetication/login in a custom API for the app using the functions of the forest? it isn't ideal to create another table "users" to do that.

Any soluton is welcome, thanks!

**Comment by SeyZ** [comment]
Hey @arthurflor I think it's a bad idea to share the authentication API between your app and your admin. The permissions / roles / etc. are completely different. So no, it's not possible and it won't :)
