### ISSUE TITLE
MSSQL - IDENTITY columns

### ISSUE THREAD

**Issue by jeremyalan** [ForestAdmin/lumber#107]
I have a simple database, 2 tables with a FK between them (one-to-many).  For the sake of this issue, let's call them Parent and Child.  Both tables have an IDENTITY column as the PK, and I'm using `lumber-cli` + Sequelize to generate models against an existing database (running locally).

Here's what I'm hoping to achieve:
- When creating new Parent records, the ID field is not editable
- When viewing Parent records, the ID field is displayed
- When editing Parent records, the ID field may be shown, but should not be editable
- When creating new Child records, the FK column should allow me to select a Parent

I've attempted to make this work, and run into the following issues:
- I can't figure out how to hide fields, e.g. the ID field on the Parent table
- If I don't specify a value, I get an error for trying to insert NULL
- If I specify a value (which I would prefer not to do, but just trying to make progress), I get an error that IDENTITY_INSERT must be enabled
- If I manually edit the models generated by `lumber-cli`, to remove the ID column from the Parent table, and restart the server, the Forest Admin UI shows an `id` column that's not specified on the Sequelize model, and I'm not really sure what to do with it or how to remove it.

I hope that's enough information, it feels like what I'm trying to do should be pretty simple, but I'm very new to this project, and I'm just struggling to get a single record created in the schema I'm working with.

I appreciate your help, and thanks for all your hard work on Forest Admin!

**Comment by arnaudbesnier** [comment]
Hi @jeremyalan,

I am sure your lumber experience would be really better with our latest lumber version `v3.3.3`.

To answer your questions:
- You can hide fields using the Admin panel "Edit Layout" mode in the context of a record details view (See more info here: https://docs.forestadmin.com/documentation/reference-guide/views/using-the-layout-editor-mode/customize-the-details-view)
- You'll have to configure you parent model to be sure it injects a default value in the `id` column on record creation (More info about Sequelize default values here: https://sequelize.org/master/manual/model-basics.html#default-values).
- If the point 2 is fixed, this one won't be relevant anymore. Just in case I found a similar Sequelize issue on Github: https://github.com/sequelize/sequelize/issues/10185
- If this id has been set by Lumber on generate, you should not remove it.

This is a very easy use case, so don't hesitate to talk to us in our Slack community channel (https://community.forestadmin.com)

As it is a very old issue, let me close it.
Feel free to re-open the ticket if your issues persist.

🌲🌲🌲
