### ISSUE TITLE
Can't access to lumber through Cloudflare

### ISSUE THREAD

**Issue by florentdestremau** [ForestAdmin/lumber#114]
I get a "CORS error" but when I ping locally the server is up and running.
What alternative other than using the Symfony bundle do I have ? I loved the idea of having the admin separated from the main source code

**Comment by arnaudbesnier** [comment]
@florentdestremau Can you provide more information about your issue? Anything that could help us understand, at which step of your process you're blocked (logs, screenshots,...). Thanks.

**Comment by florentdestremau** [comment]
I'll upload anything I can this week-end. 

From what I understand it's a problem with the fact that Cloudflare masks my server IP so the lumber service can't be detected by an external source. What I'm guessing I should do is proxying the `:3000` port on `80` with apache or nginx and link it to a domain...but then again I'm not sure that forest's app would be configurable for this.

**Comment by tyteck** [comment]
Hello and thanks for your post. It helped me to resolve the same problem.
With cloudflare you only have to pass your forest dns in "DNS only". The little grey cloud with the arrow that is passing above it.
For me that's it :)

**Comment by SeyZ** [comment]
During the `lumber generate` process, you can now set the IP/hostname and port on which your admin will be running.

It should solve your issue. Don't hesitate to reopen this issue if you are still blocked.
