### ISSUE TITLE
[Layout edition] Moving attributes fields position is more difficult than before

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/lumber#115]
Quick not to tell I'm struggling to move the attributes position since one the last updates. Thanks!

![screen shot 2017-11-09 at 10 44 42](https://user-images.githubusercontent.com/5589858/32598828-046657e0-c53b-11e7-8e7a-856aa2500d5f.png)

**Comment by arnaudbesnier** [comment]
Hey @lucasgerard, so you can't move the field, or it is just a display issue?

Do you have a field having a very long name?

**Comment by SeyZ** [comment]
Outdated?
