### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by blondie63** [ForestAdmin/lumber#117]
I've tried to install with sudo npm install -g lumber-cli
but i've this log:

77 verbose Darwin 17.2.0
78 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "lumber-cli"
79 verbose node v8.9.1
80 verbose npm  v5.5.1
81 error code 1
82 error Command failed: /usr/bin/git clone --depth=1 -q -b feature/support-schema git://github.com/ForestAdmin/sequelize.git /Users/mauro/.npm/_cacache/tmp/git-clone-df4300a2
82 error /Users/mauro/.npm/_cacache/tmp/git-clone-df4300a2/.git: Permission denied
83 verbose exit [ 1, true ]

some help ?
thanks

**Comment by SeyZ** [comment]
@blondie63 - `82 error /Users/mauro/.npm/_cacache/tmp/git-clone-df4300a2/.git: Permission denied` means you have to run your command with `sudo` first.

`sudo npm install -g lumber-cli`

**Comment by blondie63** [comment]
Take a look on attached files

 

Thanks

 

Mauro

 

Da: Sandro Munda [mailto:notifications@github.com] 
Inviato: venerdì 24 novembre 2017 10:21
A: ForestAdmin/lumber <lumber@noreply.github.com>
Cc: Mauro Miotello <info@ashnet.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [ForestAdmin/lumber] error 1 (#117)

 

@blondie63 <https://github.com/blondie63>  - 82 error /Users/mauro/.npm/_cacache/tmp/git-clone-df4300a2/.git: Permission denied means you have to run your command with sudo first.

sudo npm install -g lumber-cli
