### ISSUE TITLE
[lumber] Lumber failing to generate on adonisJS/sqlite

### ISSUE THREAD

**Issue by mathieuh** [ForestAdmin/lumber#119]
When running ```lumber generate``` I get the following error:
```(node:5978) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Please install sqlite3 package manually```
```(node:5978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
Did reinstall sqlite3 manually but it doesn't fix the issue.
I tried on this project:
https://github.com/adonisjs/adonis-blog-demo
AdonisJS framework official website:
https://adonisjs.com/

**Comment by arnaudbesnier** [comment]
Hey @mathieuh, as a workaround you could run `npm install sqlite3 -g` and it should work.

Let me know if it helps.

**Comment by mathieuh** [comment]
Hi @arnaudbesnier, yeah it works when I install it globally, thanks!

**Comment by SeyZ** [comment]
Hey @mathieuh for your information, we've fix the missing sqlite3 npm package in the package.json 👍 Thanks for report!
