### ISSUE TITLE
Bug in the website

### ISSUE THREAD

**Issue by abdussami-tayyab** [ForestAdmin/lumber#12]
Footer of your website:

> Lumber is a project from Forest. We decided to play with new ways of enabling our users with a tool that’d be completely separated from their main application, essentially creating the admin for them. If you’re in a growing company, refer to our main website to learn more about our full featureset.

Which is your "main website", maybe create an anchor link for it? Just a small fix I presume.

_Had to add an issue for this since I couldn't find a contact box_

**Comment by SeyZ** [comment]
Hey @abdussami-tayyab ! I think the text "Lumber is a project from Forest" is a link on the website: http://www.forestadmin.com/lumber

Lumber uses Forest as the admin UI: http://app.forestadmin.com

![screen shot 2016-11-14 at 22 56 07](https://cloud.githubusercontent.com/assets/519129/20296083/ae2e5c3a-aabd-11e6-9594-434592543f63.png)

**Comment by abdussami-tayyab** [comment]
Traditionally, good UX for this kind of text is underlining anchor links so they don't look like a heading.

But hey it's just a tip, if it's working for you, I must be wrong 💯
