### ISSUE TITLE
Lumber Generate doesn't support mongodb 

### ISSUE THREAD

**Issue by Aarbel** [ForestAdmin/lumber#123]
![image](https://user-images.githubusercontent.com/25119847/34853676-606de734-f735-11e7-88dc-280f7a6547ea.png)

**Comment by SeyZ** [comment]
You're right, MongoDB doesn't have the notion of "schema" so Lumber is unable to analyze it. However, Forest supports MongoDB and the easiest way to get you onboard is to start from this base repository: https://github.com/ForestAdmin/forest-examples/tree/master/examples/mongodb-database/simple

Feel free to contact us if you cannot manage it, thanks!
