### ISSUE TITLE
Port Setting on generate is not taking in account

### ISSUE THREAD

**Issue by Morikko** [ForestAdmin/lumber#125]
![capture d ecran de 2018-02-12 13-17-07](https://user-images.githubusercontent.com/7831572/36119505-688adc96-1040-11e8-9c0e-abfa5d17d625.png)

I generated with lumber and asked to use port 3500. However, it started on port 3000.
Did I misunderstand the port ?

I saw that the `./bin/www` is taking in account only the PORT env or defaulting to 3000.
https://github.com/ForestAdmin/lumber/blob/6f86b66b5eca155497f42c6b1c6ff6d8a839cdfc/templates/app/bin/www#L51

Also, by reading the code, I saw a mistake:
https://github.com/ForestAdmin/lumber/blob/c27dc160e24bd7d0ba120802b3c454c8c324af8b/lumber-generate.js#L207
The port is set to the hostname!

**Comment by SeyZ** [comment]
Thanks for reporting @Morikko ! It's now fixed.
