### ISSUE TITLE
Any plans to support NoSQL/Rethinkdb?

### ISSUE THREAD

**Issue by alitoch** [ForestAdmin/lumber#126]
Hi,
First of all, thank you for this awesome product. Are there any plans to support document-oriented databases such as Rethinkdb, or Mongodb?

Thank you!

**Comment by SeyZ** [comment]
Hey @alitoch 

Good news, we officially support MongoDB. Here's an example: https://github.com/ForestAdmin/forest-examples/tree/master/examples/mongodb-database/simple

Unfortunately, we don't plan to support RethinkDB at the moment.

Feel free to reopen this issue if needed
