### ISSUE TITLE
Invalid Date on non-nullable columns

### ISSUE THREAD

**Issue by stindall** [ForestAdmin/lumber#130]
## Expected behavior
Forest interface should do validation on data and prompt user if trying to add null values to a non-nullable column. 

## Actual behavior
For a non-nullable date column, FOREST is inserting "0000-00-00 00:00:00" as the date when the user does not set a date in the UI. Instead, FOREST should prompt user to enter a valid date or at the very least leave it null and let the update fail and show the error from the database.  You SHOULD NOT set a invalid date like "0000-00-00 00:00:00".

## Failure Logs
No errors returned -- that is the problem actually!!!

## Context

MySQL ( mariaDB  5.1.73-1+deb6u1 )

**Comment by SeyZ** [comment]
I've created a date field on my MySQL database and add it to my model:
    'birthday': {
      type: DataTypes.DATE,
      allowNull: false
    },

Now, there's frontend validation to avoid bad user input.

<img width="896" alt="screen shot 2018-05-31 at 16 08 22" src="https://user-images.githubusercontent.com/519129/40787029-df9a7386-64ec-11e8-8ff9-6163296c0ce5.png">
