### ISSUE TITLE
Image issues (Carousel + image)

### ISSUE THREAD

**Issue by juhaelee** [ForestAdmin/lumber#133]
Having a couple issues:

1) Carousel should allow a base url, similar to the image field
2) image field when uploading applies the base url, so the data:url breaks the image. base url should only be applied when image is not a dataurl

**Comment by arnaudbesnier** [comment]
Hi @juhaelee,
The `carousel` and `image viewer` widgets have been replaced by the `fileViewer` and `fileUploader`.
Those new widgets should fix the issues described here.

Let me close the issue.
Feel free to reopen it if you think it is still relevant. 🙏
