### ISSUE TITLE
Post-modification hooks

### ISSUE THREAD

**Issue by pjc0247** [ForestAdmin/lumber#136]
Hi

Is there any post-modification hooks??
I want to make a external call after fields is modified.
(Ex: publish changes to clients)

Thanks.

**Comment by arnaudbesnier** [comment]
Hi @pjc0247 
Sorry for the late reply.

I think you have 2 options here:
- Use Sequelize hooks (https://sequelize.org/master/manual/hooks.html) to configure your Lumber generated models to make external calls once the records saved.
- Regenerate a project with latest Lumber CLI version (`v3.3.3`) and extend the default controllers to make external calls (https://docs.forestadmin.com/documentation/reference-guide/routes/extend-a-route)

I hope it helps.

Let me close this ticket, feel free to re-open the issue if my suggestions does not fit your needs.

🌲🌲🌲
