### ISSUE TITLE
Intercom or Stripe integrations

### ISSUE THREAD

**Issue by lcpriest** [ForestAdmin/lumber#14]
Firstly, I love this - I have an API only app so this was an amazing addition to your suite :)

Does Lumber have all the same features as Forest? 
e.g. How do we implement an Intercom integration?

**Comment by SeyZ** [comment]
Hey @lcpriest ! Yes, it has the same feature as Forest. Lumber only generates the admin microservice, and we use the same `forest-express-sequelize` package for the admin API.

Here's the complete doc:
http://doc.forestadmin.com/developers-guide/?stack=express%2Fsequelize

**Comment by lcpriest** [comment]
Great! I installed intercom with `npm install intercom-client` and then updated `app.js` to include
```
app.use(require('forest-express-sequelize').init({
  modelsDir: __dirname + '/models',
  secretKey: process.env.FOREST_SECRET_KEY,
  authKey: process.env.FOREST_AUTH_KEY,
  sequelize: require('./models').sequelize,
  integrations: {
    intercom: {
      appId: process.env.INTERCOM_APP_ID,
      apiKey: process.env.INTERCOM_API_KEY,
      intercom: intercom,
      mapping: 'user'
    }
  }
}));
```

Is there anything else you recommend I do? I couldn't get this working.

**Comment by SeyZ** [comment]
So `intercom` comes from `var intercom = require('intercom-client');` right?

In your `models/user.js` file, are you sure the model name is `user` and not `users`?  You can check it there: `sequelize.define('HERE', {`

**Comment by lcpriest** [comment]
@SeyZ it is in fact users - thanks ;)
