### ISSUE TITLE
When JWT token is expired, the user gets stuck on the UI

### ISSUE THREAD

**Issue by facundofarias** [ForestAdmin/lumber#149]
Hello there,

We have noticed that sometimes the ForestAdmin UI hangs when the JWT is expired, and the user do not receive any warning message or advice. We didn't know what was happening, until we checked the logs and then we saw this:
```
UnauthorizedError: jwt expired
    at /opt/xxx/node_modules/express-jwt/lib/index.js:101:22
    at /opt/xxx/node_modules/jsonwebtoken/index.js:54:18
```
Not sure where I should report this.
Thanks,

Facundo

**Comment by arnaudbesnier** [comment]
Hey @facundofarias it's was a regression of the platform after a recent release.
If you refresh your browser page, it should be fixed now.

Of course, reopen the issue if you still have the issue.

🌲🌲🌲
