### ISSUE TITLE
Lumber update should take the settings from the .env file

### ISSUE THREAD

**Issue by facundofarias** [ForestAdmin/lumber#150]
Currently, every time we want to update our models, we are running `lumber update`, which detects almost all the changes (not all of them, like BOOLEAN and DATE are not taken into consideration), and then updates the model.

The thing is, that every time is asking the settings to connect to the database. Can it detect the ones that are saved into the .env file? And if there is none, then yes, ask again?
Thanks,

Facundo

**Comment by SeyZ** [comment]
Thanks @facundofarias !
