### ISSUE TITLE
update command not reading SSL option

### ISSUE THREAD

**Issue by fpinzn** [ForestAdmin/lumber#155]
Checking the generate command, the SSL option is read here

https://github.com/ForestAdmin/lumber/blob/a93eff0d3a19da6726f6232e289805d4f9bc6ee3/lumber-generate.js#L30-L46

That same option is missing from the update command. I believe the other options are not pertinent during an update.

https://github.com/ForestAdmin/lumber/blob/a93eff0d3a19da6726f6232e289805d4f9bc6ee3/lumber-update.js#L26-L36

**Comment by SeyZ** [comment]
Fixed in the 1.14.1
