### ISSUE TITLE
BelongTo OK but corresponding hasMany not generated

### ISSUE THREAD

**Issue by prevostc** [ForestAdmin/lumber#156]
I have a 1-n relationship between categories and category domains.
Lumber successfully generate the belongTo association for the category model, but do not generate the hasMany for the category domain model. 

In the interface, I can follow a link in the category list, but I can't list categories for a single domain (coherent with the generated models).

How to generate the hasMany relationships?

**Comment by arnaudbesnier** [comment]
Hi @prevostc, I think the answer is here: https://doc.forestadmin.com/developer-guide/lumber.html#adding-the-relationships

I close this issue but don't hesitate to reopen it if you're not satisfied with the answer ;)

🌲🌲🌲
