### ISSUE TITLE
error: 💀  Ouch, cannot connect to the database 💀

### ISSUE THREAD

**Issue by craigtsmith** [ForestAdmin/lumber#16]
we don't have a user set or password.
Lumber doesn't like this it seems.

local development
macOS
postgresql
rails project

**Comment by craigtsmith** [comment]
works fine with another local rails project using mysql with root

**Comment by SeyZ** [comment]
Hey @craigtsmith what do you mean by "we don't have a user set or password." ? I fixed a similar issue if I well understood yours here: #17 

Can you confirm me it's ok now?

**Comment by macchie** [comment]
i think what he means is that postgres on rails locally doesnt use user/password

**Comment by macchie** [comment]
I found a solution @craigtsmith, use your user name for postgres login. it works.

**Comment by SeyZ** [comment]
@macchie The username is always required, isn't it?
