### ISSUE TITLE
Lumber does not generate models for views

### ISSUE THREAD

**Issue by ValentinPerret** [ForestAdmin/lumber#161]
Hello, I don't know if it is an issue or more a feature request, but lumber does not seems to generate models for the views available in my `postgres` DB (it does generate models for my SQL tables but not for my SQL views.) 
Is there a way to access my views in Forest using Lumber?

**Comment by ValentinPerret** [comment]
Hi @arnaudbesnier , thanks for your answer. I tried to do that but I don't understand how to add a missing view in the `models` directory. I succeeded to add manually `tables` but I could not find how to add a `view`.

**Comment by arnaudbesnier** [comment]
I think you declare a model base on a View the same way you declare all the models based on Tables.

Can you share an example of model declaration you tried to make you SQL View visible in Forest?

Thanks.

**Comment by ValentinPerret** [comment]
I tried the following model to make a view visible in forest (the view is called `vessel_inventory` in the DB):
`'use strict';

module.exports = (sequelize, DataTypes) => {
  var Model = sequelize.define('vessel_inventory', {
    'quantity': {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'vessel_inventory',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });
  Model.removeAttribute('id');

  Model.associate = (models) => {
    Model.belongsTo(models.equipment, {
      foreignKey: 'equipment_id',
      targetKey: 'equipment_id',
      as: '_equipment_id',
    });
    
    Model.belongsTo(models.vessel, {
      foreignKey: 'vessel_id',
      targetKey: 'vessel_id',
      as: '_vessel_id',
    });
    
  };
  return Model;
};`

Below is what is in my db when I `select * from vessel_inventory`:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/15217445/44609929-a89fe780-a7ae-11e8-80a4-2fcfd1efe53b.png">

However when I look at what is displayed on forest I get the following:
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/15217445/44609949-c705e300-a7ae-11e8-8ed5-9c0ff2964548.png">

Do you have an idea why I have one row duplicated 4 time in forest?

**Comment by arnaudbesnier** [comment]
The reason is that Forest cannot display the records list properly if the collections does not have a primary key. You can either add one `id` column in your view or declare a composite primary key based on `vessel_id` and `equipement_id` if you are sure that the combinaison is unique.

Check the Sequelize documentation to see how to use the `primaryKey: true` parameter).

**Comment by ValentinPerret** [comment]
Hi @arnaudbesnier, thanks for the help.
Because my view is built from a query on my DB using an aggregation function is was hard to add an id column. I ended up using the compounded primary key route method in the model definition and it works fine! 😃 
Keep the good work your tool is amazing! 
If you could add a paragraph about recovering views in the doc it would be perfect for the next person trying to get their views working! 😍

**Comment by arnaudbesnier** [comment]
Glad to hear everything works now.

We have plans to improve the doc with a section about SQL Views that could be released in the next weeks. 

🌲🌲🌲
