### ISSUE TITLE
Lumber update command update the public schema

### ISSUE THREAD

**Issue by ValentinPerret** [ForestAdmin/lumber#162]
Hello,
I realized that the command `lumber update` update my model based on my DB public schema even if a specific schema is referenced in my `.env` file. This is annoying because I want lumber to update only one specific schema and I don't want to generate a model for my public schema.

**Comment by htmathias** [comment]
@ValentinPerret 
I'm having this issue too.

**Comment by htmathias** [comment]
I'm now getting this error on public:

```error: 💀  Oops, your database is empty. Please, create some tables before running Lumber generate.💀```

How do I update the models manually?

**Comment by arnaudbesnier** [comment]
I am pretty sure this issue is now fix with the latest Lumber versions.
Let me close the ticket and feel free to reopen it if the issue persists on your side.
