### ISSUE TITLE
[Question] Not able to change smart Field Enum

### ISSUE THREAD

**Issue by KevinL59** [ForestAdmin/lumber#163]
Hi everybody!

I have a problem trying to create a smart Field Enum. This smart enum his here to select a currency. I succeed to create this smart Field, display it on our forest admin, but I not able to change it. I add a set method to the smart Field, I test many different ways to implement this function, but I not able that work. The documentation doesn't help me. What can I do to permit to set this field on the forest dashboard?

```
{
    field: 'currency_capital',
    type: 'Enum',
    enums: ["EUR", "USD", "GBP"],
    get: function (object) {
      return this.enums[0]; // "EUR" by default
    },
    isReadOnly: false,
    set: function (object, value) {

      //  What to insert here?

    }
}
```
Thank you for your help.

**Comment by arnaudbesnier** [comment]
Hi @KevinL59, I am not sure to understand.

To help you with the implementation of the `set` function, we need to have a concrete example of the "business logic" you want to implement for the `get` function of the Smart Field.

Can you share with us this logic?

Thanks.

**Comment by KevinL59** [comment]
Thanks, Arnaud for your answer.

We have several fields that represent money (Capital, fundraise, etc...). For each of those fields, I want to choose a currency. That why I want to put an enum field with the currency next to each money fields I have.

But the logic to implement the set function looks complicated to understand.

Thank you for your answer

**Comment by jqrn** [comment]
I have the same problem, or a similar one. My Smart Field shows up in the table view and also in the detail view, with the correct values. I thought that if I supplied a `set` function, then when I clicked on Edit on an item's detail, that Smart Field would be editable rather than read-only. But my Smart Fields are staying readonly regardless of whether I'm supplying a `set` or not.

**Comment by KevinL59** [comment]
Ok I misunderstand the concept of smart fields. I will find another way to add this currency information. thanks for you answer.
