### ISSUE TITLE
Support for my existing REST API

### ISSUE THREAD

**Issue by haggen** [ForestAdmin/lumber#168]
Hey there,

I see that `lumber generate` requires a SQL database, but I also saw in the examples that you support MongoDB, so I was wondering; does Lumber support any REST API? For instance I have an API but I don't have an interface to manage the data. Would Lumber help me?

Thanks in advance.

**Comment by SeyZ** [comment]
Hey @haggen - Nope, Lumber is a tool to generate an Express.js application where we install `forest-express-[orm]` package on it to create a Rest API dedicated for your admin operations. This API will be 100% compatible with forestadmin.com - so you cannot use your application's API, which have a different purpose.
