### ISSUE TITLE
SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: 

### ISSUE THREAD

**Issue by craigtsmith** [ForestAdmin/lumber#17]
```
SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
```

Noticed this in autoenv notice:

```
autoenv:     DATABASE_URL=mysql://root:undefined@localhost:3306/
```

i wonder if that 'undefined' is causing issues.

**Comment by SeyZ** [comment]
Thanks @craigtsmith for report!
You're right, the `DATABASE_URL` was incorrect. Can you update it in `.env` file with the value:
`DATABASE_URL=mysql://root@localhost:3306/`

It's not fixed for new projects.
