### ISSUE TITLE
`lumber update` detects every field as newly added

### ISSUE THREAD

**Issue by cirokd** [ForestAdmin/lumber#170]
Hello!

Every time I run `lumber update`, it runs seemingly without any issues, but it outputs what I believe is every single field we have in our database, saying that it detected a new field, but cannot add the definition automatically. I wouldn't mind having to add newly detected fields manually as it outputs exactly what I would have to insert to the models, but it's impossible to find the new fields when it lists every single field. The output is the same for every run.

Here is a screenshot of some of the output (this goes on and on):

![image](https://user-images.githubusercontent.com/13242163/45479986-2ae55100-b748-11e8-94c9-76c7d37c4494.png)

Thank you for investigating this issue!

**Comment by joeellis** [comment]
Also hitting this - any ideas what is causing it?

**Comment by SeyZ** [comment]
Hey @cirokd and @joeellis - I've tried to reproduce the issue with Lumber update on my side but everything works well.

Can you share a model file where you simulate to remove a field from the model definition? 

If Lumber says: "Cannot add the field definition…", it means Lumber cannot detect the content layout generated "by default". Did you change something on this file? If so, you need to add the detected new field manually.

**Comment by cirokd** [comment]
Yes @SeyZ, we have added the relationships manually, that may be the source of this issue.

**Comment by cirokd** [comment]
Is there any way this issue could be fixed?

**Comment by SeyZ** [comment]
I'm not sure it's an issue. Lumber does not recognize the syntax of your model file so it suggests you to add manually the new detected fields.

What's the issue with this behavior?

**Comment by cirokd** [comment]
The issue is that it lists _every_ field (new and old) as newly detected. I would be happy to add the new fields manually if it only listed them.

**Comment by SeyZ** [comment]
@cirokd ok I think this is because Lumber is unable to detect the declared fields from your model file. Can you share your model file to analyze the syntax?

Thanks!

**Comment by cirokd** [comment]
@SeyZ sure, this is one example of a model that hasn't changed since the initialization of the project, but both its fields are listed as newly added on every `lumber update`:
```
'use strict'

module.exports = (sequelize, DataTypes) => {
  var Model = sequelize.define(
    'sample_type',
    {
      type_id: {
        type: DataTypes.STRING,
        primaryKey: true
      },
      description: {
        type: DataTypes.STRING
      }
    },
    {
      tableName: 'sample_type',
      underscored: true,
      timestamps: false
    }
  )

  Model.associate = models => {}

  return Model
}
```

**Comment by SeyZ** [comment]
Hi @cirokd - I have released a fix.

The problem was due to the model indentation file. Don't know who has changed it.
So, I've improved the regexp to be more permissive on the file syntax
