### ISSUE TITLE
Unable to login to forest admin project

### ISSUE THREAD

**Issue by ps06756** [ForestAdmin/lumber#171]
Hi,
I created a sample database to try out forest admin along with lumber, but I am unable to get it to work.
After installing `lumber-cli`, I generated the project directory using `lumber-cli` which ran successfully without error.
After that I did, `npm install` and `npm start`.
After that, I navigated to `http://app.forestadmin.com` as instructed after doing `npm start`.  
Now, when I try to login to my project, I keep getting the error "Your password is incorrect, please try again".
I have checked that my password is actually correct. How can I resolve this error ?  I have tried this setup on two different machines (with Ubuntu and Mac).

**Comment by SeyZ** [comment]
@ps06756 thanks for reporting. I'm currently working to fix this critical bug

**Comment by SeyZ** [comment]
Fixed 👍

**Comment by Arjun-sna** [comment]
@SeyZ This is happening still. Not able to use Forestadmin completely.

**Comment by arnaudbesnier** [comment]
Hi @Arjun-sna,

As this issue is pretty old, I am not sure that the issue is the same even thought the resulting experience looks to be the same.

Feel free to join the community at http://community.forestadmin.com.
It is the best way to get help.
