### ISSUE TITLE
Error on lumber update with a non default schema

### ISSUE THREAD

**Issue by lmwattebled** [ForestAdmin/lumber#175]
💀  Oops, your database is empty. Please, create some tables before running Lumber update.💀

This is what I get when trying to do a "lumber update".
The previous "lumber generate" operation was done without any problem.

Lumber version 1.12.0

is there a fix?

**Comment by SeyZ** [comment]
Hey @lmwattebled - What's your database type? Do you use a non-default schema?

**Comment by lmwattebled** [comment]
Hi,
This is postgresql.
And yes, as indicated in the title ;), I am using a non default schema.

Thanks in advance for your help.

**Comment by lmwattebled** [comment]
Hi,
This is postgresql.
And yes, as indicated in the title ;), I am using a non default schema.

Thanks in advance for your help.

**Comment by lmwattebled** [comment]
Hi guys,

May I have an update on this issue?
Or at least is there a workaround to that "lumber update" issue?

Indeed, I need to study the possibility to build our back office with Forest, and it will not be possible without this required feature.

Thanks in advance for your help

**Comment by SeyZ** [comment]
@lmwattebled The fix is now available in the `1.12.1` version

**Comment by lmwattebled** [comment]
Yeah that works now!
Many thanks for your help.
