### ISSUE TITLE
Can't install from npm install -g lumber-cli

### ISSUE THREAD

**Issue by nicolasdupere** [ForestAdmin/lumber#182]
Here the error message when installing (same problem with SUDO):

--> ~ $ npm install -g lumber-cli
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
/Users/nicolasdupere/.npm-global/bin/lumber -> /Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/lumber.js

> sqlite3@4.0.2 install /Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.2/node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.2 and node@11.2.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.2 and node@11.2.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3240000/sqlite3.c
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3240000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o
rm: ./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o.d.raw: No such file or directory
  LIBTOOL-STATIC Release/sqlite3.a
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3
node-pre-gyp ERR! node -v v11.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
  CXX(target) Release/obj.target/node_sqlite3/src/database.o~install: Failed to exec install script
../src/database.cc:3:10: fatal error: 'macros.h' file not foundstall: Failed to exec install script
#include "macros.h"
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3/lib/binding/node-v67-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/nicolasdupere/.npm-global/lib/node_modules/lumber-cli/node_modules/sqlite3
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nicolasdupere/.npm/_logs/2018-11-20T15_08_38_264Z-debug.log
--> ~ $

**Comment by SeyZ** [comment]
Hi @nicolasdupere - I tried with the *Node version 11.2.0* and I got the same error message.

Can you try again using another version like the LTS one? *Node 10.13.0* ? For me, it fixed the problem.

It's not the first time that node-sqlite3 does not support newest version of Node (see https://github.com/mapbox/node-sqlite3/issues).

I'm wondering if I should not remove sqlite support in Lumber :(

**Comment by SeyZ** [comment]
Hi @nicolasdupere - Can we speak in english here for other people?

Did you install Nodejs 10.13.0 using NVM? It seems your NODE_PATH environment variable is not well set and so, your shell is not able to find the lumber executable.

At this point, I think it's more like an issue to solve on your Node install/configuration than a real lumber problem.

But, we will close this issue as soon as we removed SQLite support. It's not the first time the node-sqlite3 repository break our Lumber tool when a new Node version is released. So thanks for the notice!

**Comment by nicolasdupere** [comment]
Ok we found the problem. 

Let me recap. 

1- To install ForestAdmin, you really need to install, from node website (No nvm or other versionning app) the latest LTS version of node. Not the last version available. 

2- When this finally work, i was not able to launch lumber generate. Why? I got always: Could not found. We fix the problem by adding export PATH=$PATH:~/.npm-global/bin in the .bash_profile.

Now everything is fine.

You can close the case.
