### ISSUE TITLE
[*] MongoDB Atlas - Does not work with Free plan (mapReduce() function not allowed)

### ISSUE THREAD

**Issue by louisteenbrink** [ForestAdmin/lumber#184]
I have a FREE MongoDB Atlas account and during Lumber generate it thrown the following error: 

`error: 💀  Oops, operation aborted 💀 due to the following error:  message=CMD_NOT_ALLOWED: mapreduce, stack=MongoError: CMD_NOT_ALLOWED: mapreduce`

**Comment by SeyZ** [comment]
Fixed

**Comment by gsm4** [comment]
hi, i´m trying to learn mongoDB with the atlas free account and give me this error

2019-07-04T16:53:38.683-0700 E QUERY    [js] Error: map reduce failed:{
        "ok" : 0,
        "errmsg" : "CMD_NOT_ALLOWED: mapreduce",
        "code" : 8000,
        "codeName" : "AtlasError"
} :

**Comment by marcperrinp** [comment]
Hi @gsm4, does your issue have anything to do with Lumber and/or Forest Admin?

**Comment by arnaudbesnier** [comment]
Hi guys,

Let me reopen the issue.
Some warnings have been added to explain that this error may come from the Mongo Atlas Free Tier limitation.
So far, you have no other choice than to upgrade to a Mongo Atlas paying plan.

We'll try to investigate in the coming weeks on how to support Mongo Atlas Free plan with Lumber. 

🌲🌲🌲

**Comment by saifsmailbox98** [comment]
Is this something we can expect getting fixed in the near future?

**Comment by louisteenbrink** [comment]
@saifsmailbox98 we don't have an ETA for this, unfortunately. However, you'll find a workaround in our [help center](https://help.forestadmin.com/article/does-forest-admin-work-with-mongodb-atlas/).

You can do a local installation (using a local DB to mirror the atlas one) to generate your project and then change the data source from local to the Atlas DB. (The idea is to bypass Atlas limitation to still be able to generate a project locally, and then plug it to the remote DB).

**Comment by Scra3** [comment]
Hello, this issue is fixed since this [release](https://github.com/ForestAdmin/toolbelt/commit/4602030b757a0f1c28449fece9ac5fab4ab3d9ff)
