### ISSUE TITLE
lumber generate not response

### ISSUE THREAD

**Issue by blackcatpolice** [ForestAdmin/lumber#187]
Type : lumber generate , 
? What's the database type?  mysql
? What's the database name? xxxxx
? What's the database schema? [optional]
? What's the database hostname? (remoteserver)
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]  
? Does your database require a SSL connection?  No        
? What's the IP/hostname on which your back office will be running?  localhost
? What's the port on which your back office will be running?e running?  3013
? Choose a name for your back office:  faceadmin
? What's your email address?  xxxxx@gmail.comcom
? Choose a password:  **************

and this programe not response anything .

Why ...

**Comment by SeyZ** [comment]
Hey @blackcatpolice - It was a problem from a dependency (inquirer) used to ask for inputs. The problem is now fixed in the Lumber version 1.14.0 after upgrading inquirer.

Can you confirm? Thanks for report!
