### ISSUE TITLE
lumber-cli installation not properly working (lumber: command not found)

### ISSUE THREAD

**Issue by wlegate** [ForestAdmin/lumber#188]
I'm following the installation instructions on the ['Installation' page](https://docs.forestadmin.com/lumber/getting-started/installation)… the "lumber-cli" package appears to install successfully (no warnings or errors), but the "lumber" bash command isn't found after installation.

Not sure if this is an issue with outdated documentation or something else…

**Details**
- I've tried both installing thee lumber-cli globally and within my project directory
- Using MacOS v10.14.3, Node v11.0.0, and NPM v6.4.1

**Comment by SeyZ** [comment]
Hi @wlegate 

Just did it on a fresh new install and it works well. It's probably due to your PATH? Does it work with another package with a command line bin?

![image](https://user-images.githubusercontent.com/519129/50835505-2546f300-1357-11e9-9bcd-f3b7f6c31beb.png)

**Comment by equilibrium123** [comment]
Where and how  can I access my lumber cli? I have got it installed. I have use npm lumber -version  in my command line and it gave me the version.

I have use the same command line to type Lumber login and it is not recognized. I need to connect with my mysql database. I use a windows system.

Please help.

**Comment by promisepreston** [comment]
> Where and how can I access my lumber cli? I have got it installed. I have use npm lumber -version in my command line and it gave me the version.
> 
> I have use the same command line to type Lumber login and it is not recognized. I need to connect with my mysql database. I use a windows system.
> 
> Please help.

This Stackoverflow answer should help:

[Lumber: Command 'lumber' not found](https://stackoverflow.com/a/59549276/10907864)
