### ISSUE TITLE
Running the admin UI locally

### ISSUE THREAD

**Issue by montanaflynn** [ForestAdmin/lumber#19]
Great looking project, however I'm uncomfortable sending my database credentials to a third-party.

The gif in the README shows that at the end of setting up you get a subdomain on forestadmin.com, is there any way to instead run the server / website locally?

**Comment by SeyZ** [comment]
Hey @montanaflynn !

You never send your database credentials to a 3rd party! The database credentials are use to generate an app (the admin microservice) on your computer.

The hosted part is only for UI, which **never** have access to your data :)

**Comment by montanaflynn** [comment]
Thanks for the quick reply @SeyZ! 

I think this should be noted in the README.md in case anyone else has the same reservations I had.

**Comment by SeyZ** [comment]
@montanaflynn You're right! Could you send a pull request? I can do it if you prefer, let me know :)

**Comment by montanaflynn** [comment]
@SeyZ I'll defer to you

**Comment by SeyZ** [comment]
@montanaflynn README are now updated. I've just added:
`Your database credentials are safe. They are only stored in the Lumber generated microservice.`

Thanks :)
