### ISSUE TITLE
Env variables should be prefixed with "FOREST_"

### ISSUE THREAD

**Issue by luxcem** [ForestAdmin/lumber#192]
Some `process.env` variables are prefixed with "`FOREST`" like `FOREST_AUTH_SECRET` and `FOREST_ENV_SECRET` but other like `DATABASE_URL`, `SSL_DATABASE`, `ENCRYPT_DATABASE`, `DEV_RENDERING_ID`, `DATABASE_SCHEMA` are not.

To avoid interferences with other process, env variables should all be prefixed with "`FOREST`"

**Comment by arnaudbesnier** [comment]
Hi @luxcem,
We've improved the environment variables names consistency:
```
APPLICATION_HOST=...
APPLICATION_PORT=...

DATABASE_URL=...
DATABASE_SCHEMA=...
DATABASE_SSL=...
DATABASE_ENCRYPT=...

FOREST_AUTH_SECRET=...
FOREST_ENV_SECRET=...
```

As Lumber generates an admin api micro-service, no risk to interfere with other "process" I think.
Let me close the ticket and feel free to reopen the issue if you have a use case in mind.

🌲🌲🌲
