### ISSUE TITLE
Array?

### ISSUE THREAD

**Issue by htmathias** [ForestAdmin/lumber#195]
`type: DataTypes.ARRAY(DataTypes.STRING)`

The system that automatically defines the model doesn't read my array.
Still undefined when updating myself.
Is this a known issue?

**Comment by htmathias** [comment]
You can absorb as a string, which outputs fine within the Data View.
However, search & other functions depend on  the SQL command ```LOWER``` and you  can't  lower  an array.

Only workaround  is  to cast the array to a string when  you're  done appending to it.

**Comment by arnaudbesnier** [comment]
Hi @htmathias,

Thanks for the feedback.
I am not sure to understand exactly what is your issue.

Forest Admin manages properly Arrays (of String, Enums, Number,...) for CRUD operations.
You're right about the current implementation, the native search does not query the Array columns.

Being said, can you detail what is your need and what you observe in details?

Thank you for your help.

**Comment by arnaudbesnier** [comment]
As we didn't receive any update for 10 month, I'll close this ticket.
Feel free to re-open it with a detailed context if the issue persists.

🌲🌲🌲
