### ISSUE TITLE
lumber generate fail

### ISSUE THREAD

**Issue by on99** [ForestAdmin/lumber#2]
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? adx
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]
? Choose a project name:  adx
(node:2007) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'dbName' of undefined

**Comment by SeyZ** [comment]
Hey @on99 - Do you have the full stacktrace?

**Comment by on99** [comment]
@SeyZ  Sorry I even do not have a forest admin app account, is it possible to use lumber without that?

**Comment by on99** [comment]
What I want is to create an admin panel for database management :-) Seems like lumber is doing exactly the same thing, I did not go through the document yet.

**Comment by SeyZ** [comment]
When you run `lumber generate` - the tool asks you to fill your database details and an email/password for the Forest registration. You don't need to have a Forest account before running the Lumber generate :)

**Comment by nicgutierrez** [comment]
Hey @on99, @SeyZ: I'm getting the exact same error

**Comment by on99** [comment]
@SeyZ Yep I enter email/password, but I got `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'dbName' of undefined` error. How can I get full stack trace for you?

**Comment by on99** [comment]
```
 ✘  ~  lumber generate
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? adx
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]
? Choose a project name:  admin
? What's your email address?  random@gmail.com
? Choose a password:  *********
(node:4449) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'dbName' of undefined
```

**Comment by SeyZ** [comment]
Hey @on99 and @nicgutierrez 
What's your OS?

**Comment by vladimir-yuldashev** [comment]
+1, macOS Sierra

**Comment by SeyZ** [comment]
Hey @on99 @vladimir-yuldashev @nicgutierrez 

I've reproduced your issue and it's fixed in the version `1.0.4`. Can you upgrade `lumber-cli` and try again?

**Comment by vladimir-yuldashev** [comment]
@SeyZ 

It works now! But how can I delete unused projects now? I have 12 of them :)

**Comment by SeyZ** [comment]
Oops :D :D :D Can you tell me the email used or the project names?

**Comment by vladimir-yuldashev** [comment]
@SeyZ vladimir@fondbot.com

**Comment by SeyZ** [comment]
@vladimir-yuldashev I deleted your old projects. I think you're all good now :)

Guys, feel free to reopen the issue if you still have the problem :)

**Comment by on99** [comment]
@SeyZ I am using macOS Sierra.

Here is the output after I upgrade to the latest version:

```
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? adx
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]
? Choose a project name:  admin
? What's your email address?  nanohugh@gmail.com
? Choose a password:  *********
error: 💀  Ouch, cannot create your account 💀
```

Should I enter a new email account every time I need to create a project? I deleted `~/.lumberrc` before executing `lumber generate`. 🤕

**Comment by nicgutierrez** [comment]
hey @on99, @SeyZ: I was getting the same error but then I tried with a different email address and it worked fine. What is the email address inserted being used for?

**Comment by pojda** [comment]
I'm trying to test here but no luck :(

```
$ lumber generate
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? lumber
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]  
? Choose a project name:  lumber_test
? What's your email address?  (hidden)@gmail.com
? Choose a password:  ******
error: 💀  Ouch, cannot connect to the database 💀
```

I'm feeling kinda frustrated for not being able to spit some debug info here.

I can connect to my mysql locally no problem. I tried giving the root password, and not giving it (it's saved on my ~/.my.cnf).

My system:
Mac El Capitan (10.11.6)
npm v 3.10.3
lumber v 1.0.1 (I ran "npm -g upgrade", "npm -g upgrade lumber-cli" but I can't seem to get v 1.0.4, maybe this is it?)

**Comment by SeyZ** [comment]
@on99 Ok got it. I think your admin account was in a bad state. You can see your current logged user with `$ lumber user` , login with `$ lumber login` and logout with `$ lumber logout`.

You don't have to remove the file manually. When the first project is well configured, you can create new ones without any problem.
