### ISSUE TITLE
Create new related data form fail the first time

### ISSUE THREAD

**Issue by JSilversun** [ForestAdmin/lumber#205]
## Description
When I try to Add a new related data from any model, the form is not shown the first time, but if I try to open it again, the form is shown and work without errors.

## Example
I have the models: `Category` with `id` and `icon`, `CategoryTranslation` with `name` and `description`.

I added the relationship in sequalize like this: 

```js
// models/category.js
module.exports = (sequelize, DataTypes) => {
  const Model = sequelize.define('category', {
    'icon': { type: DataTypes.STRING},
  }, {
    tableName: 'category',
    timestamps: false,
  });
  Model.associate = (models) => {
    Model.hasMany(models.category_translation, {foreignKey: 'category_id'});
  };
  return Model;
};
```
```js
// models/category_translation.js
module.exports = (sequelize, DataTypes) => {
  const Model = sequelize.define('category_translation', {
    'name': {
      type: DataTypes.STRING,
    },
    'description': {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'category_translation',
    timestamps: false,
  });

  Model.associate = (models) => {
    Model.belongsTo(models.category, {
      foreignKey: 'category_id',
      as: '_category_id',
    });
    Model.belongsTo(models.language, {
      foreignKey: 'language_id',
      as: '_language_id',
    });
  };
  return Model;
};
```
When I go to the `forest admin` interface, I see the `translations` in the related data section (I changed its name to Translations).

![image](https://user-images.githubusercontent.com/26018221/55030075-ee8d8a00-4fe1-11e9-837b-4a111e47fdb0.png)

When I hit the `Create new category translation`, nothing is shown: 
![image](https://user-images.githubusercontent.com/26018221/55030228-49bf7c80-4fe2-11e9-9a82-127c037b037e.png)

There you can see the JavaScript error that is thrown.

If you click `Translations` and click the `Create new category translation` button again, you will see this time the form is correctly shown without any errors in the console:

![image](https://user-images.githubusercontent.com/26018221/55030543-00bbf800-4fe3-11e9-82ef-d7b7000ed3ab.png)

**Comment by yonathan9669** [comment]
Hey @marcpforestadmin, same here!! good @JSilversun quite detailed issue description 👍🏼

**Comment by arnaudbesnier** [comment]
Hi @JSilversun, thanks for the valuable feedback.
We'll look at this regression today 👍 
I'll let you know.

**Comment by arnaudbesnier** [comment]
Hi guys, it should be fixed now.
Can you refresh you browser page twice and try again to confirm the issue has gone?

**Comment by JSilversun** [comment]
Yes, it works, thank you very much for your quick response!
