### ISSUE TITLE
HTML as response doesn't allow javascript execution

### ISSUE THREAD

**Issue by jorgetbGitHub** [ForestAdmin/lumber#206]
Currently I'm trying to create a form using the "Custom html response" feature exposed in the documentation. There I cannot use javascript, for some reason the content inside of <script> tag finally is shown as simple text. 
How can I execute js? Would be possible use of JQuery, Bootstrap and other libraries? 

Thanks.

**Comment by marcperrinp** [comment]
Hi @jorgetbGitHub, 

We don't support the <script> tag in the 'html' property mentioned [here](https://docs.forestadmin.com/documentation/reference-guide/actions/create-and-manage-smart-actions#custom-html-response).

However, we have a big project in our roadmap to make Smart actions more powerful. Would you mind sharing what you wanted to build on [this ticket](https://portal.productboard.com/forestadmin/1-forest-open-product-roadmap/c/61-logic-jump-in-smart-action-forms) of our public roadmap?
