### ISSUE TITLE
Custom base application url when using lumber-generate

### ISSUE THREAD

**Issue by losteed** [ForestAdmin/lumber#21]
Hello there !

I can't wait to see this great tool connected on my project :)

lumber-generate ended successfully on my webserver (i'm not working on localhost)

However, I get
"Login
Oops, cannot reach your application. Are you sure it is running?"

because I'm not able to enter my custom base url, for instance
http://www.myproject.com:8080 instead of http://localhost:3000

How can I fix this setting, from https://app.forestadmin.com (or from the command line tool) ?

**Comment by SeyZ** [comment]
Hey @losteed !

Lumber generates the admin microservice on `http://localhost:3000`. I'm not sure to understand your question. Do you want to push the microservice remotely or use another local URL?

**Comment by losteed** [comment]
Well, I may have missed something...

Actually, there is nothing on my localhost. 
The whole project is hosted elsewhere, on a dedicated server, and accessible through a remote url (like www.myproject.com)

I ran "lumber generate" there, but once logged on http://app.forestadmin.com/, my browser tries to connect on http://localhost:3000 (where there is nothing to see) and i don't know how to change that.


Thanks for your consideration.
