### ISSUE TITLE
isRequired property ignored for smart fields

### ISSUE THREAD

**Issue by JSilversun** [ForestAdmin/lumber#213]
## Description
If you create a `smart field` with the `get` and `set` method, and you set `isRequired=true`, `forest` will mark the field as required but ignore it in the form submission.

## Example

```js
// forest/board.js
const Liana = require('forest-express-sequelize');
const models = require('../models');
const {board} = models;

Liana.collection(board.name, {
  fields: [
    {
      field: 'rawr',
      type: 'String',
      isRequired: true,
      get: (instance) => {
        return 'jsnow';
      },
      set: (instance, value) => {
        return instance;
      },
    },
  ]
});
```
Then after the server is running the form for the model Board will look something like:

![image](https://user-images.githubusercontent.com/26018221/55577321-5aa67700-56e1-11e9-99a9-6088aab540ee.png)

If you complete the fields required by the database but leave the smart fields empty, you will be able to create the record:

![image](https://user-images.githubusercontent.com/26018221/55577429-95a8aa80-56e1-11e9-94b1-e60bc70c0f77.png)

**Comment by yonathan9669** [comment]
@SeyZ we were trying to do a work around for this using hooks but we had another issue with them that push us back here.

We described the issue here #215

**Comment by arnaudbesnier** [comment]
Hi @JSilversun @yonathan9669,
This is now fixed and the patch is directly available if you refresh your browser page.

Thanks for your patience
🌲🌲🌲
