### ISSUE TITLE
Sequelize hooks not working as expected

### ISSUE THREAD

**Issue by JSilversun** [ForestAdmin/lumber#215]
## Description
I have an `area` collection with a smart field `name`,  and I want to implement a hook after an area is `created`/`updated` to do something with the smart field I declared, but none of the following hooks are being called: `afterCreate`, `afterUpdate`, `afterBulkUpdate`, `afterSave`.

[Here](http://docs.sequelizejs.com/manual/hooks.html) are the docs of the hooks of `sequelize`, there you can see the expected flow.

The only hook that is been actually called is: `afterValidate` but this is being called 3 times.

```js
// models/area.js
module.exports = (sequelize, DataTypes) => {
  const Model = sequelize.define('area', {
    'geometry': {
      type: DataTypes.GEOMETRY,
    },
  }, {
    tableName: 'area',
    timestamps: false,
  });
  return Model;
};
```
```js
// forest/area.js
const Liana = require('forest-express-sequelize');
const {area} = require('../models');
const hooks = ['afterCreate', 'afterUpdate', 'afterBulkUpdate', 'afterValidate', 'afterSave'];
Liana.collection('area', {
  fields: [
    {
      field: 'name',
      get: (instance) => {
        return 'jsnow';
      },
      set: (instance) => {
        return instance;
      },
    },
  ],
});

for (const hook of hooks) {
  area.addHook(hook, `${hook}${area.name}Hook`, () => {
    console.log(hook);
  });
}
```
When I ranned this example and try to edit an `area`:

![image](https://user-images.githubusercontent.com/26018221/55909627-8b3b5480-5baa-11e9-8363-fcd7b5a658cd.png)

I will get this in the server output:

```
OPTIONS /forest/area/1 200 0.254 ms - 2
GET /forest/area/1 200 33.995 ms - 687
SELECT "id", "geometry", "parent_id", "area_type_id" FROM "area" AS "area" WHERE "area"."id" = '1';
afterValidate
afterValidate
afterValidate
PUT /forest/area/1 200 120.717 ms - 687
```

I read some of your code and find out that the hooks are being called in `dist/services/resource-updater.js` in the `perform` method:
```js
// dist/services/resource-updater.js
// ...
this.perform = function () {
    var compositeKeysManager = new CompositeKeysManager(model, schema, newRecord);

    return new ResourceFinder(model, params).perform().then(async function (record) {
      if (record) {
        _.each(newRecord, function (value, attribute) {
          record[attribute] = value;
        });
        return record.validate().catch(function (error) { //< --- THIS is the first call to validate method
          throw new ErrorHTTP422(error.message);
        }).then(function () {
          return record.save(); // <--- The save method generates two calls to the afterValidate hook
        });
      }
    })
```

Maybe the problem is that the other hooks are not actually working, I saw you created some sort of schema on top of the models' definitions on the `models` folder so maybe that's why the hooks I define are not being called, can you guide me on how to get the hooks working?

**Comment by yonathan9669** [comment]
This is actually quite important, because we are not been able to run some business logic for those actions that are needed. Do you think @marcpforestadmin this is a bad/wrong implementation on us? or it's actually a bug, because we already tried different things without any luck.

**Comment by JSilversun** [comment]
I found a workaround for this issue, the problem was caused because any change to a smart field won't mark the sequelize model instance as `changed` if you debug any model instance you will see an attribute `_changed` which is an object which each key matches an attribute that changed, to force the update hook to trigger, just "trick" the ORM to think any field that is NOT virtual, changed
something like `instance._changed['id']=true`
