### ISSUE TITLE
Lumber installed, but cannot access lumber cli from  my desktop cmd

### ISSUE THREAD

**Issue by equilibrium123** [ForestAdmin/lumber#216]
Where and how can I access my lumber cli? I have got it installed. I have use npm lumber -version in my command line and it gave me the version.

I have use the same command line to type Lumber login and it is not recognized. I need to connect with my mysql database. I use a windows system.

Please help.

**Comment by marcperrinp** [comment]
Hi @equilibrium123 , can you provide more details on your issue? What command are you running? What is the error logs?

**Comment by marcperrinp** [comment]
An installation walkthrough is available [here](https://docs.forestadmin.com/documentation/getting-started/installation/install-in-lumber#install-using-npm) using npm.

Feel free to reopen this thread if you still encounter problems during your installation process. Also, don't hesitate to ask questions in our [Slack community](http://community.forestadmin.com/) where you might get a quicker response.
