### ISSUE TITLE
Export layout config

### ISSUE THREAD

**Issue by JSilversun** [ForestAdmin/lumber#217]
## Description
Sometimes when we develop, some errors occur and then, the layout config resets, this is a big problem because we do a lot of manual setups like putting icons or ordering fields, or choose which field of a collection will be used as a reference.

I didn't find any way to export the config, so in case an error occurs, we can import the config again.

Is there an alternative to preserve the config in case of failure? Thanks in advance!

**Comment by marcperrinp** [comment]
Hi @JSilversun , unfortunately there isn't at the moment. However:

1/ There shouldn't be any errors in your layout configurations. Please do let us know via our [Slack community](http://community.forestadmin.com/) if this happens again;
2/ We have plans to enable layout configuration versioning. You can follow [this card](https://portal.productboard.com/forestadmin/1-forest-open-product-roadmap/c/51-store-the-layout-config) of our public roadmap to check its evolution.
