### ISSUE TITLE
Release Docker image

### ISSUE THREAD

**Issue by Betree** [ForestAdmin/lumber#219]
Hello!

I saw that that https://hub.docker.com/r/forestadmin/lumber exists but it doesn't have any description and doesn't seems maintained.

Releasing docker images would be great for people running clusters in Docker Swarm / Kubernettes where you usually have secret files and don't allow connections to your DB from the outside.

Do you have plans to do that?

**Comment by marcperrinp** [comment]
Hi @Betree , that Docker image is maintained as well as [https://hub.docker.com/r/forestadmin/lumber-forestadmin](https://hub.docker.com/r/forestadmin/lumber-forestadmin) which allows you to install Lumber and its Forest Admin plugin in one shot.

We are actually currently working on a new installation process where using Docker is an option. It still needs work but you can already test it by following our documentation at https://docs.forestadmin.com/documentation/getting-started/installation/install-in-lumber#install-using-docker.
