### ISSUE TITLE
No description found for "databasechangeloglock" table. Check the table name and schema; remember, they _are_ case sensitive.

### ISSUE THREAD

**Issue by psantwani** [ForestAdmin/lumber#223]
I am using Postgres and the tables having been seeded using liquibase.

**Comment by 201Factory** [comment]
:+1: +1

**Comment by tobiaskneubuehler** [comment]
Same problem here. I fixed some bugs by myself, maybe I will commit a PR. For now you can use version 1.14.3 of lumber-cli for postgres with schema support

**Comment by arnaudbesnier** [comment]
Hi @psantwani,

Thanks for the feedback!
Could you share:
- the name of this table in your Postgresql database?
- the model generated by Lumber in your admin backend?

It would help a lot!

**Comment by arnaudbesnier** [comment]
@VincentMolinie do you think Lumber `v2.2.4` fixes this issue?

**Comment by VincentMolinie** [comment]
Fixed by version `v2.2.4`
