### ISSUE TITLE
Lumber Install Issues

### ISSUE THREAD

**Issue by LiquidNexxus** [ForestAdmin/lumber#225]
npm install -g lumber-cli
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm ERR! path /usr/local/lib/node_modules/lumber-cli/node_modules/sequelize
npm ERR! code EISGIT
npm ERR! git /usr/local/lib/node_modules/lumber-cli/node_modules/sequelize: Appears to be a git repo or submodule.
npm ERR! git     /usr/local/lib/node_modules/lumber-cli/node_modules/sequelize
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXXXXX/.npm/_logs/2019-05-29T09_27_37_449Z-debug.log

**Comment by slimee** [comment]
I have only the WARN, which is "just" a deprecation warning, but no errors.

What's your config?

Mine is Windows 10 + git bash + node v8.11.4

**Comment by fccoelho7** [comment]
The same here!

```
➜  admin git:(master) npm install -g lumber-cli
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm ERR! path /usr/local/lib/node_modules/lumber-cli/node_modules/sequelize
npm ERR! code EISGIT
npm ERR! git /usr/local/lib/node_modules/lumber-cli/node_modules/sequelize: Appears to be a git repo or submodule.
npm ERR! git     /usr/local/lib/node_modules/lumber-cli/node_modules/sequelize
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fabiocoelho/.npm/_logs/2019-06-04T13_50_35_498Z-debug.log
```

**Comment by marcperrinp** [comment]
This appears to be a git/npm-related issue (See [https://github.com/react-native-community/react-native-safe-area-view/issues/73](https://github.com/react-native-community/react-native-safe-area-view/issues/73)).

Closing until further notice.
