### ISSUE TITLE
Lumber generate : can't use arrow keys

### ISSUE THREAD

**Issue by vichenze** [ForestAdmin/lumber#23]
Hello,

I am unable to use the arrow keys to select switch database type to mysql. Well actually I use them but it doesn't change anything. I'm using Windows and I've tried several consoles (Standard cmd, Babun, etc), none worked.
Is it possible to type in the type instead ?

Thanks

**Comment by SeyZ** [comment]
Hey @vichenze - We use https://github.com/SBoudrias/Inquirer.js for the prompt. It seems to be an issue on their side.

https://github.com/SBoudrias/Inquirer.js/issues/303
Is it helpful?

**Comment by SeyZ** [comment]
@vichenze I fixed the issue by using a `rawlist` on Windows :)

Feel free to reopen this issue if needed.

**Comment by vichenze** [comment]
Thanks for your quick fix. Unfortunately it still don't work for me. What a rawlist is supposed to change ?

BTW, there is a difference in your version number between Github (1.0.9) and your code (1.0.10). Not much, but it can be confusing :)

**Comment by SeyZ** [comment]
Hey @vichenze Did you try with the 1.0.10 version?
