### ISSUE TITLE
Deployment - How to deploy into Azure function

### ISSUE THREAD

**Issue by ductranit** [ForestAdmin/lumber#230]
Hi there,
I wonder whether I can deploy into Azure function?. I use Mongoose to connect Mongo db successful on local. Then I follow this tutorial https://ahmadawais.com/microsoft-azure-functions-javascript/ to deploy it into Azure function. 
I already set production environment variable for forest key & secret. 
I also run `npm install` on Azure
But when I copy the function url into ForestAdmin dashboard, it can't be recgonized.
Could you please help me with the Azure guide?

**Comment by arnaudbesnier** [comment]
Hi @ductranit,

Can you join our community Slack channel to have help from the team and the community to setup you Azure function?
You can access it here: http://community.forestadmin.com/

**Comment by arnaudbesnier** [comment]
Hi @ductranit ,
Did you eventually managed to deploy on Azure?

**Comment by ductranit** [comment]
Hi @arnaudbesnier, sorry for late response. My requirements were changed, I didn't use Mongo db anymore. Instead that, I use cosmos database with SQL API, so I couldn't use ForestAdmin.
Last time I tried ForestAdmin on Azure app service instead of Azure function and it could work with cosmos db Mongo API
