### ISSUE TITLE
[*] Lumber Update - New tables not added on production from lumber update

### ISSUE THREAD

**Issue by dylanhusted** [ForestAdmin/lumber#233]
I'm facing an issue with updating our production Forest Lumber models. By running lumber update, I was able to successfully update all models locally.

However, when I pushed to production (Heroku), only column additions to existing tables were added. New tables were not added on production.

I can't just run 'heroku run lumber update', and I'm not sure what else to do, other than push the local code after running lumber update locally.

**For example:**
- New column 'email' would be added to an existing 'users' table
- New table 'tweets' would not be added

Is there something I'm missing here, or is this a possible bug?

**Comment by arnaudbesnier** [comment]
Hi @dylanhusted,
Could you provide the lumber version you're using?

Do you have a `.forestadmin-schema.json` in your admin api server generated by Lumber?
If so, do you have the new table `tweets` listed in it?

Thanks.

**Comment by dylanhusted** [comment]
Hi @arnaudbesnier , sorry for the late reply.

The `.forestadmin-schema.json` file is in our admin API server on Heroku, and it does have 'tweets' listed in it, though 'tweets' was an arbitrary example, and in our case, the new tables are actually called 'communities' and 'memberships'. 

As for our lumber version, we are using lumber-forestadmin v1.0.5.

Looking at the production codebase, I'm also seeing models listed for communities and memberships. I do see they're both missing a line that is in all of our other models though:

`schema: process.env.DATABASE_SCHEMA,`

Could that be the root of the issue? Everything else looks fine.

**Comment by arnaudbesnier** [comment]
Hi @dylanhusted ,

Good point about the missing `schema` property.
Did you try to add those lines manually and deploy the code on your production server?
Does it make your models appear in production?

Thanks

**Comment by arnaudbesnier** [comment]
This issue may be related to this fix then:
https://github.com/ForestAdmin/lumber/pull/236

**Comment by dylanhusted** [comment]
No, I didn't try that actually. That PR appears to be doing the same thing, so I'll wait until it's fully merged in and give it a try.

Thanks for taking the time to review and address this issue so far @arnaudbesnier .

**Comment by dylanhusted** [comment]
It's true that this issue is now resolved, but I did have to go back and manually insert `schema: process.env.DATABASE_SCHEMA,` in the models that were generated before PR #236 was merged in. 

Models generated after that seemed to work out of the box.
