### ISSUE TITLE
Lumber update generating invalid camelCase fields

### ISSUE THREAD

**Issue by JoeAlamo** [ForestAdmin/lumber#250]
## Expected behavior

When running `lumber update` I expect it to create fields that match the fields in the tables in my database so when I deploy these changes to my admin panel API, my Forest Admin installation is able to make API calls to my backend to create or update records.

## Actual behavior

`lumber update` is creating duplicate fields in a camelCase fashion. All of my fields in the table are in underscore_case. Since upgrading to lumber 2.3.2 it has been adding fields with camelCase.

## Failure Logs

Model definition before running update (previously lumber was unable to detect our `id` field which was UUID.)

```javascript
module.exports = (sequelize, DataTypes) => {
  const Model = sequelize.define('address', {
    'active': {
      type: DataTypes.BOOLEAN,
    },
    'created_at': {
      type: DataTypes.DATE,
    },
    'updated_at': {
      type: DataTypes.DATE,
    },
    'address_line_1': {
      type: DataTypes.STRING,
    },
    'city': {
      type: DataTypes.STRING,
    },
    'country': {
      type: DataTypes.STRING,
    },
    'postcode': {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'address',
    underscored: true,
    
    schema: process.env.DATABASE_SCHEMA,
  });

  Model.associate = (models) => {
  };

  return Model;
};
```

Model definition after running update

```javascript
module.exports = (sequelize, DataTypes) => {
  const Model = sequelize.define('address', {
    'addressLine1': {
      type: DataTypes.STRING,
    },
    'updatedAt': {
      type: DataTypes.DATE,
    },
    'createdAt': {
      type: DataTypes.DATE,
    },
    'id': {
      type: DataTypes.UUID,
      primaryKey: true 
    },
    'active': {
      type: DataTypes.BOOLEAN,
    },
    'created_at': {
      type: DataTypes.DATE,
    },
    'updated_at': {
      type: DataTypes.DATE,
    },
    'address_line_1': {
      type: DataTypes.STRING,
    },
    'city': {
      type: DataTypes.STRING,
    },
    'country': {
      type: DataTypes.STRING,
    },
    'postcode': {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'address',
    underscored: true,
    
    schema: process.env.DATABASE_SCHEMA,
  });

  Model.associate = (models) => {
  };

  return Model;
};
```

## Context

Before updating to 2.3.2 we were having problems with lumber not detecting our id primary key fields which are UUID type. After upgrading it has detected these but now the camelCase issue is here.

* Lumber Package Version: 2.3.2
* Database Dialect: postgresql
* Database Version: 10.6

**Comment by arnaudbesnier** [comment]
Hi @JoeAlamo ,
Thanks for the report. It is strange that you have single quotes around your field names because Lumber 2.3.2 is not supposed to generate the models like that.

Maybe the `update` command does not work well with projects created with an older version of Lumber. Can you check and confirm that you're using Lumber v2.3.2?

Thanks for your help

**Comment by JoeAlamo** [comment]
I'm using lumber v2.3.9 now and still the same issue. Should I delete all of my models and then run generate??

**Comment by arnaudbesnier** [comment]
Yes, I think the solution is to remove all your models, and then run `lumber update`.
Be sure that your models are versioned in order to check the diff and ensure that nothing will be lost (relationships, custom code changes,...)

**Comment by JoeAlamo** [comment]
That fixed it :)
