### ISSUE TITLE
Not works on my windows 10 machine

### ISSUE THREAD

**Issue by ahmetoz** [ForestAdmin/lumber#26]
``` command
cd test && npm install...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
versions:

npm : 3.10.8
nodejs : v6.9.1

**Comment by Pitt05** [comment]
Same problem... :'(

**Comment by tvarsis** [comment]
Yeah, this is broken on Windows. It's the spawn process that doesn't work as read here:
http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

I swapped it out, but then it blows up on an other part instead. It should be really easy for the developers to replicate if they have a Windows machine. Pretty much just run lumber generate and it will break. I used Postgres on a localhost, if that would matter. Windows 10, node 6.3.

**Comment by SeyZ** [comment]
Hey guys, do you have `npm` installed on your Windows machine and directly accessible in your console?

**Comment by tvarsis** [comment]
Yes. 3.10.3

**Comment by ahmetoz** [comment]
Yes I have `npm` version **3.10.8**

**Comment by Unforgiven-wanda** [comment]
Same issue on W10 Pro with Node 6.9.1 and npm 3.10.8.

**Comment by tvarsis** [comment]
Any progress on this?

**Comment by SeyZ** [comment]
Hey guys,

I've just published the version `1.1.2` that supports Windows 10. Can you try again with that version?

Feel free to reopen the issue if the problem still persists.

**Comment by Pitt05** [comment]
20 error Windows_NT 10.0.10586
21 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--prefix=Tintin" "--progress=true"
22 error node v6.9.1
23 error npm  v3.10.8
24 error code EISDIR
25 error errno -4068
26 error syscall read
27 error eisdir EISDIR: illegal operation on a directory, read
28 error eisdir This is most likely not a problem with npm itself
28 error eisdir and is related to npm not being able to find a package.json in
28 error eisdir a package you are trying to install.
29 verbose exit [ -4068, true ]

Not working... :/

**Comment by SeyZ** [comment]
@Pitt05 if you go on your `Tintin` directory and you run `npm install` manually, is it working?
