### ISSUE TITLE
How to use Lumber inside of my express application?

### ISSUE THREAD

**Issue by ernaneluis** [ForestAdmin/lumber#262]
Currently, the lumber generates another server to run in another port, how to install lumber to work inside of the same express.js application?

**Comment by arnaudbesnier** [comment]
Hi @ernaneluis,
We do not officially support it anymore but the idea would be to install:
- https://github.com/ForestAdmin/forest-express-sequelize if you have a SQL database
- https://github.com/ForestAdmin/forest-express-mongoose if you have a NoSQL database
as a middleware in your existing Express server.

Feel free to join our community to have direct answers and support:
https://community.forestadmin.com/

🌲🌲🌲
