### ISSUE TITLE
Cannot POST //sessions

### ISSUE THREAD

**Issue by iCoderzDev** [ForestAdmin/lumber#263]
I'm getting 404 after deploying on my production server

Error message say's

Unlock your data
Oops, cannot reach the endpoint on your application. Check your Liana version.

**Comment by arnaudbesnier** [comment]
Hi @iCoderzDev,

There is a lot of reasons that could explain such error message.
Does it work perfectly in your development environment?

Could you provide a detailed description of your deployment issue with:
- the hosting platform you use,
- the logs of your production server on start,
- the logs of your production server on liana login trial,
- the liana version you use,
- any specific configuration you would have in production you don't have in development,
- ...

Thanks for your help.
