### ISSUE TITLE
Error when generate an app with MongoDB when having view (CommandNotSupportedOnView)

### ISSUE THREAD

**Issue by gianpaj** [ForestAdmin/lumber#265]
```
$ lumber generate -c mongodb://localhost/data Proj

? What's the database schema? [optional]
? Does your database require a SSL connection?  No
? What's the IP/hostname on which your application will be running?  localhost
? What's the port on which your application will be running?  3310
> Cannot generate your project.
> An unexpected error occured. Please create a Github issue with following error:
{ MongoError: Namespace onova-data.orders_completed is a view, not a collection
    at Connection.<anonymous> (/opt/bitnami/nodejs/lib/node_modules/lumber-cli/node_modules/mongodb/lib/core/connection/pool.js:466:61)
```

## Context

* Lumber Package Version: 2.4.0
* Database Dialect: ?
* Database Version: MongoDB v4.0.12

**Comment by rap2hpoutre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix mongo DB views](https://trello.com/c/AM1birnd/3799-fix-mongo-db-views)

**Comment by rap2hpoutre** [comment]
Hi @gianpaj! Thank you for your contribution!

I just submitted a Pull Request here to fix your problem: https://github.com/ForestAdmin/lumber/pull/289.  🎉. It should be merged soon and be released in the next Lumber release. Stay tuned!
