### ISSUE TITLE
Oops, cannot reach your application. Are you sure it is running?

### ISSUE THREAD

**Issue by jcoulaud** [ForestAdmin/lumber#27]
Hi,
First of all, great job guys :)

Little problem here. I got the following message when I try to login in the admin UI:
```
Login 
Oops, cannot reach your application. Are you sure it is running?
```
even though I'm sure it's running on my server. Tested it on Chrome and Safari.

Best,
julien

**Comment by SeyZ** [comment]
Hey @jcoulaud Can you run a curl in your terminal and show me the output?
`$ curl -I http://localhost:3000/forest`

Thanks!

**Comment by jcoulaud** [comment]
`curl: (7) Failed to connect to localhost port 3000: Connection refused`

**Comment by SeyZ** [comment]
Hey @jcoulaud So it means your server is not running :( Did you run the `node ./bin/www` in your folder?

**Comment by jcoulaud** [comment]
Sorry for the output, yes it was running but I was on the wrong server when I executed the command.
Here it is : 
`$ curl -I http://localhost:3000/forest
HTTP/1.1 204 No Content
X-Powered-By: Express
Date: Fri, 18 Nov 2016 20:00:53 GMT
Connection: keep-alive`

**Comment by jcoulaud** [comment]
But still the same message when I'm on the UI Interface :/

**Comment by jcoulaud** [comment]
Hi ! Any news :) ?

**Comment by SeyZ** [comment]
Hey @jcoulaud ! Sorry about the delay

So you're server is running but the browser can't make requests to it. Do you have errors on your Chrome console?

**Comment by jcoulaud** [comment]
Hey !
So when I try to login, I have this message in the center top
`Login 
Oops, cannot reach your application. Are you sure it is running? If your application is running, you might have a CORS configuration issue.`

And in the console
`OPTIONS http://localhost:3000/forest/sessions net::ERR_CONNECTION_REFUSED`

**Comment by SeyZ** [comment]
Ok it seems to be a CORS issue. Normally, your microservice injects the right CORS headers in the http request but it does not seems to work with yours. 

Do you have the cors middleware there?
https://github.com/ForestAdmin/lumber/blob/master/templates/app/app.js#L21

**Comment by jcoulaud** [comment]
Oh :/ Yes I have it

**Comment by jcoulaud** [comment]
Hi there !
I would like to give it a shot again, so can you help me please :) ?
Do you have any idea what's could cause the CORS issue ?
Best

**Comment by SeyZ** [comment]
Hey @jcoulaud can you drop me an email (sandro@forestadmin.com) to schedule a quick call to help us figure out what happens with your CORS problem ?

**Comment by Permpkin** [comment]
I have the same issue, when asked for the password it spits out "http://localhost:3000/forest/sessions net::ERR_CONNECTION_REFUSED" in the console. Is this supposed to be setup locally? I had set it up on a VPS?

**Comment by SeyZ** [comment]
@Permpkin it's suppose to work with a localhost URL without any problem. We can investigate more your issue in details if you drop me an email sandro@forestadmin.com ;)

**Comment by Notifium** [comment]
Hi,
Is there any solution to this?I'm getting the exact same issue:curl responds with 204 code, ERR_CONNECTION_REFUSED in console.

Regards,
Andy

**Comment by Permpkin** [comment]
@Notifium It seems to be ( as Seyz mentioned ) designed to work with "localhost" ( rather than on a remote VPS ). Try setting it up on your local machine ( That's how I resolved the ERR's ).

**Comment by adrianricardo** [comment]
any update here? I'm getting the same error on localhost. Production works just fine

**Comment by samshinde** [comment]
Does any one came across below issue

**Comment by samshinde** [comment]
My forest server was not running. No all things are going smoothly.  :+1:

**Comment by anilprasad** [comment]
I am getting the similar error as mentioned above 
🌳 Open your admin UI: http://app.forestadmin.com 🌳
[forest] 🌳🌳🌳
VError: IP Whitelist error: Forest server request error: Not Found
...and the remaining part as mentioned by @samshinde

**Comment by kaleb** [comment]
Same issue. This is what I get when I run `curl -I http://localhost:3002/forest`:

```
HTTP/1.1 204 No Content
X-Powered-By: Express
Vary: Origin
Access-Control-Allow-Credentials: true
Date: Tue, 18 Jun 2019 22:17:33 GMT
Connection: keep-alive
```

**Comment by seyhunak** [comment]
Any update of this? Forest requests get 204 response.

> OPTIONS /forest/sessions 204 0.119 ms - 0
> GET /forest/sessions 404 12.255 ms - 1425

**Comment by Yani06** [comment]
Same issue  for trying to unlock data  ! is there any solution?
RequestURL: http://localhost:3000/forest/sessions
Response : Connection Refused

**Comment by manthis** [comment]
I'm having the exact same issue. Nothing in the logs of my application and the CORS policy is alright. Don't know what's the problem here.

**Comment by manthis** [comment]
Ok I solved the issue by adding this to my CORS configuration in Express:

`const app = express();

    // We configure CORS
    let corsOptions = {
        origin: 'https://app.forestadmin.com',
        credentials: true,
    };
    app.use(cors(corsOptions));`

**Comment by unicolai42** [comment]
> Same issue. This is what I get when I run `curl -I http://localhost:3002/forest`:
> 
> ```
> HTTP/1.1 204 No Content
> X-Powered-By: Express
> Vary: Origin
> Access-Control-Allow-Credentials: true
> Date: Tue, 18 Jun 2019 22:17:33 GMT
> Connection: keep-alive
> ```

Try with an other port (For example 3003 rather than 3000). Its works for me.

**Comment by navjinder** [comment]
Hi There

I am seeing the same issues [see image]
![image](https://user-images.githubusercontent.com/3472650/64643208-e5e90e80-d3dd-11e9-942f-be9a473c217c.png)

**Comment by serhanbalci** [comment]
Still not working.

**Comment by arnaudbesnier** [comment]
Hi @serhanbalci,

This error message can occur in various cases.
How did you validate that you server is running?
Can you also provide details about your issue?

Thanks for your help 🙏

**Comment by serhanbalci** [comment]
I solved in development mode, but there is no documentation for production. I did not find any useful piece of docs publish it for production. Is there any ? thanks

**Comment by promisepreston** [comment]
I put up an awesome Medium article here for anyone interested in integrating **Forest Admin** in **Rails Application**: 

https://medium.com/@promisepreston/up-and-running-with-forest-admin-in-rails-aa63599e9adc

**Comment by arnaudbesnier** [comment]
Hi guys, as mentioned in the past:
> This error message can occur in various cases.
> How did you validate that you server is running?

This message comes from an expected error.
It usually means that your admin backend server is not running or properly configured.

Let me close this issue, as there is no clear action to do here for the Forest Admin team.
