### ISSUE TITLE
Database connection using SSH

### ISSUE THREAD

**Issue by Appsido** [ForestAdmin/lumber#28]
Is there a way to do so ? Because database is hosted on remote server but can connect only using SSH usr/ssh key.

**Comment by SeyZ** [comment]
Hey @Appsido I'm not sure to understand what you mean by "can connect only using SSH key" ? In your app, what form has your database connection string?

**Comment by Appsido** [comment]
Hey @SeyZ as per my understanding of the lumber usage is to deploy on my local machine and connect to a remote database. But my remote database is accessible only using SSH connection. In fact my question is obsolete since it has to be done locally with a SSH tunneling.

Another solution is to install lumber on my remote server but i need to have a "virtual host" listening on port 80 to route to port 3000.

I'll close my issue because the problem is due to infrastructure.
