### ISSUE TITLE
Running the project entirely offline

### ISSUE THREAD

**Issue by Unforgiven-wanda** [ForestAdmin/lumber#29]
Hello,
I was curious if it is at all possible to run the project **entirely** offline; and by that I mean both logic and UI. I have some clients who could be interested in this service were it not dependent on an all-time stable internet connection.

I have an inkling what the answer will be, just had to ask. You never know.
Thank you.

**Comment by SeyZ** [comment]
Hey @Unforgiven-wanda Unfortunately the UI is only available remotely :(

**Comment by kudos** [comment]
@SeyZ you say unfortunately like it was unavoidable, but then why did you build it this way? I guess you have plans to monetise it at some point? You need to be more clear that this is some hybrid model you have used, and not the obvious model that would be expected.
