### ISSUE TITLE
Install forest-admin plugin fails: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Sorok-Dva** [ForestAdmin/lumber#294]
Hi,

~I'm trying to generate my first lumber project following the steps shown on your website or trought lumber generate CLI command~. (Solved by upgrading mysql from 5.7 to 8)

I now try to finish the installation by executing the final command `lumber install lumber-forestadmin ...`

The command do not success, I tried to add the NODE_TLS_REJECT_UNAUTHORIZED process env but it just throwing me a warning and still have the same error and also tried `npm config set strict-ssl=false`

Thanks,

## Failure Logs
```
> Cannot connect to the database due to the following error:
> SequelizeConnectionError: self signed certificate in certificate chain
```

## Context

* Lumber Package Version: 2.5.1
* Database Dialect: mysql
* Database Version: 8.0.18

**Comment by xnfa** [comment]
https://github.com/ForestAdmin/lumber/pull/302 solved this problem

**Comment by Sorok-Dva** [comment]
Thank you, but what we need to do to get this fix ? 

I tried `npm i -g lumber-cli` to update the package but I still get the error

**Comment by Sorok-Dva** [comment]
Thanks but we we need to do to get this fix ?

I tried `npm i -g lumber-cli` and `npm -i lumber-forestadmin` but I'm still getting the same error.

Thanks

**Comment by rap2hpoutre** [comment]
Hi @Sorok-Dva, thank you for contributing! :+1:

I just released Lumber [a few minutes ago](https://www.npmjs.com/package/lumber-cli). It includes a fix that may solve your problem:

> Command Generate - Fix MySQL connection failure without SSL

More info [here](https://github.com/ForestAdmin/lumber/blob/devel/CHANGELOG.md#fixed) and [there](https://github.com/ForestAdmin/lumber/pull/302). 

You have to reinstall lumber-cli @ version `2.5.2` (the latest version)

Let me know if it works now! Thanks you for your patience.

**Comment by rap2hpoutre** [comment]
> #302 solved this problem

You are right! Thank you for your help!

**Comment by Sorok-Dva** [comment]
Hi @rap2hpoutre ! Thanks for your quick answer !

I tried `npm i -g lumber-cli@2.5.2` but I'm getting NPM error : 

```
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/lumber-cli failed, reason: unable to get local issuer certificate
```

`npm i -g lumber-cli@latest` installs version 2.5.1

Is there something that I missed ?

**Comment by Sorok-Dva** [comment]
Anyway it's ok, the NPM error was due to the test I tried to solve this problem at the beginning (`npm config set strict-ssl false` fix the npm error)

Running the command `lumber install lumber-forestadmin` now working fine ! Thanks for this quick hotfix @rap2hpoutre !
