### ISSUE TITLE
nothing happens 

### ISSUE THREAD

**Issue by danielsitnik** [ForestAdmin/lumber#3]
Nothing happens when I run it, tried with and without sudo.
It just ends without any kind of error message, and nothing is generated in the folder.

The usual success messages that are shown in the video like "Hooray, installation success!" and "Run your admin microservice" are not displayed at all.

Ubuntu 16.
Node 6.5.0

```
daniel@sputnik:~/bikedafirma/lumber$ sudo lumber generate
Enter your database connection details and then your admin interface will be automatically generated.

? What's the database type?  mysql
? What's the database name? bikedafirma
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]  
? Choose a project name:  bblumber
daniel@sputnik:~/bikedafirma/lumber$ 
```

**Comment by Aubron** [comment]
This is the same situation that I am experiencing. Willing to provide additional details or logs as will help.

**Comment by SeyZ** [comment]
Hey @Aubron Are you on Windows, Linux or OSX ? Can you also tell me the version? Thanks :)

**Comment by Aubron** [comment]
So this was on an Ubuntu 16.04 with the sudo apt-get install nodejs version of Node. This was resolved by using n to install node latest.
