### ISSUE TITLE
Issue with install while extracting inquirer to gunzTa?

### ISSUE THREAD

**Issue by JustJasper** [ForestAdmin/lumber#30]
Having an issue completing the install of lumber, resulting in the install being killed:

```
user@domain:~$ sudo npm install -g lumber-cli
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
extract:inquirer → gunzTa ▐ ╢███████████████████████████████████████░░░░░░░░░░╟
Killed
user@domain:~$ 
```

Installing on a Digital Ocean droplet, using Node.js v4.2.6 and NPM v3.5.2

**Comment by JustJasper** [comment]
Ah, disregard - I was running out of memory, and hadn't set up a swap file.

**Comment by SeyZ** [comment]
Great to hear @JustJasper 👍
