### ISSUE TITLE
Error generating MongoDB mapCollection syntax error (with fix)

### ISSUE THREAD

**Issue by transitive-bullshit** [ForestAdmin/lumber#313]
## Expected behavior

Generating a project with a MongoDB connection string should work.

## Actual behavior

**Lumber connects successfully to the database but fails during the map-reduce analysis of collections with a JS syntax error**.

I've circumvented the issue with the project generation succeeding by changing `services/analyze-mongo-collections.js` `mapCollection` function to not use newer ES features:

```js
function mapCollection() {
  var keys = Object.keys(this);
  for (var i = 0; i < keys.length; ++i) {
    var key = keys[i];
    var val = this[key];
    if (this[key] instanceof ObjectId && key !== '_id') {
      emit(key, 'mongoose.Schema.Types.ObjectId');
    } else if (this[key] instanceof Date) {
      emit(key, 'Date');
    } else if (typeof this[key] === 'boolean') {
      emit(key, 'Boolean');
    } else if (typeof this[key] === 'string') {
      emit(key, 'String');
    } else if (typeof this[key] === 'number' && key !== '__v') {
      emit(key, 'Number');
    }
  }
}
```

The above version parses fine but the current repo version [here](https://github.com/ForestAdmin/lumber/blob/devel/services/analyze-mongo-collections.js#L17-L34) causes the error below.

Why would this happen for me and not other users? I'm really not sure. See my environment below for more details, but I think you're better off changing the `mapCollection` implementation to not use ES6 features to be safe against this issue in the future anyhow.

## Failure Logs

```
> An unexpected error occured. Please create a Github issue with following error:
MongoError: SyntaxError: invalid for/in left-hand side :
functionExpressionParser@src/mongo/scripting/mozjs/mongohelpers.js:48:25

    at Connection.<anonymous> (/Users/tfischer/.nvm/versions/node/v12.7.0/lib/node_modules/lumber-cli/node_modules/mongodb/lib/core/connection/pool.js:466:61)
    at Connection.emit (events.js:203:13)
    at processMessage (/Users/tfischer/.nvm/versions/node/v12.7.0/lib/node_modules/lumber-cli/node_modules/mongodb/lib/core/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (/Users/tfischer/.nvm/versions/node/v12.7.0/lib/node_modules/lumber-cli/node_modules/mongodb/lib/core/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1572749822 },
  ok: 0,
  errmsg: 'SyntaxError: invalid for/in left-hand side :\n' +
    'functionExpressionParser@src/mongo/scripting/mozjs/mongohelpers.js:48:25\n',
  code: 139,
  codeName: 'JSInterpreterFailure',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1572749822 },
    signature: { hash: [Binary], keyId: [Long] }
  },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

## Context

* Lumber Package Version: `2.6.2`
* Database Dialect: MongoDB
* Database Version: Version 4.0.13 (hosted on cloud.mongodb.com)
* Node.js Version: v12.7.0

Note that I used `ndb` to debug where the error was happening and trace its root cause to the mapCollections function during database analysis.

**Comment by VincentMolinie** [comment]
Hi @transitive-bullshit , Can you confirm that it works on 2.6.3 ?

**Comment by transitive-bullshit** [comment]
Confirmed. Thanks!
