### ISSUE TITLE
When running lumber generate - Unhandled 'error' event

### ISSUE THREAD

**Issue by sandboxhack** [ForestAdmin/lumber#33]
lumber generate
ℹ︎  Enter your database connection details and then your admin interface will be automatically generated.
ℹ︎  Your database credentials are safe. They are only stored in the Lumber generated microservice.

? What's the database type?  postgres
? What's the database name? root
? What's the database hostname? localhost
? What's the database port? 5432
? What's the database user?  root
? What's the database password? [optional]  ****
? Choose a project name:  proaj

cd proaj && npm install...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by SeyZ** [comment]
Hey @sandboxhack

• Do you have `npm` installed on your computer?
• What's your OS?

Thanks!

**Comment by sandboxhack** [comment]
Windows 10 
Yes NPM installed

**Comment by SeyZ** [comment]
Hey @sandboxhack I've just published the version `1.1.2` that supports Windows 10. Can you try again with that version?

Feel free to reopen the issue if the problem still persists.

**Comment by sandboxhack** [comment]
![lumber](https://cloud.githubusercontent.com/assets/21955080/20873896/804e89dc-bad2-11e6-9b8a-8fa17d431d6e.PNG)
Error !
