### ISSUE TITLE
Unrecognized data type for field <field_name>

### ISSUE THREAD

**Issue by alexparker** [ForestAdmin/lumber#35]
Everything worked smoothly so far, until I wanted to change a model field to be a checkbox instead of an input field for a boolean property. It seems lumber mapped the field TINYINT(1) to be DataTypes.INTEGER. So I manually changed the line in the `models/model_name.js` file to be `type: DataTypes.BOOLEAN` 

When restarting lumber, the error I get is `Model creation error: Error: Unrecognized data type for field <field_name>`

**Comment by arnaudbesnier** [comment]
Hi @alexparker,
As this issue is pretty old, and Lumber changed a lot in 3 years, I am not sure this error is still relevant. Let me close it.

If the issue persists with Lumber v3 feel free to reopen the ticket or create a new one.

🌲🌲🌲
