### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by on99** [ForestAdmin/lumber#36]
I click the `Deploy` button in `http://app.forestadmin.com/` to deploy from Development to Production then access the admin panel via the email you sent me, but error prompt from web 
`Login 
Forest cannot retrieve any users for the project you're trying to unlock.` 
and 
`[forest] 🌳🌳🌳  Cannot retrieve the project you're trying to unlock. Can you check that you properly copied the Forest secret key in the forest_liana initializer?` 
from the console. 

I've already set `env.FOREST_SECRET_KEY.value` to the `secret_key` from Production environment.

**Comment by SeyZ** [comment]
Hey @on99 

Did you push your generated admin on a remote server with the correct `FOREST_SECRET_KEY` as an environment variable? Can you tell me where you deployed your admin? AWS? Heroku?

**Comment by on99** [comment]
@SeyZ Sorry I didn't realize `FOREST_SECRET_KEY` should be set as an environment variable... I deploy it on aws.
