### ISSUE TITLE
SequelizeDatabaseError: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by michellekong85** [ForestAdmin/lumber#367]
Generate a new backend application hit : 
An unexpected error occurred. Please reach out for help in our Slack community or create a Github issue with following error: SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json) = uniqueIndexes THEN NULL
              ELSE uniqueIndexes
            END' at line 9

**Context**
TODO: Please provide any relevant information about your setup.
Database: MySQL 5.6

**Comment by arnaudbesnier** [comment]
Hi @michellekong85,

Thank you for the valuable feedback, I guess you are using Lumber v3.1.0.
It looks like a compatibility issue with MySQL 5.6 (as our integration tests are made on MySQL 5.7).
We'll try to look at it

As a workaround could you try with Lumber v3.0.1 (`npm install lumber-cli@3.0.1`) it should generate your project properly.

**Comment by michellekong85** [comment]
hi @arnaudbesnier,
Tried install lumber v3.0.1 cannot solve. Any other suggestions?
Thanks.

**Comment by arnaudbesnier** [comment]
Hi @michellekong85, do you have the same error?
I am asking because the SQL query that fails using v3.1.0 should not exist in v3.0.1.

**Comment by arnaudbesnier** [comment]
Hi @michellekong85 

This issue should be fixed in Lumber v3.3.1.
Let me close the issue, feel free to re-open it if the problem persists.

🌲🌲🌲
