### ISSUE TITLE
Update generated project

### ISSUE THREAD

**Issue by loicgriffie** [ForestAdmin/lumber#37]
Hi,

I have done a lumber generate command at version 1 of my project API. Then i have done enhancements to the API to reach version 2. I'd like to update the version 1 project to version 2 but can't find a way to do it. Unless remove local generated project and do lumber generate again. But i now got 2 projects with same name. Is there at least a way to delete a project unless i can't update a project ?

Thanks

**Comment by SeyZ** [comment]
Hey @Appsido 
You're right, we need a `lumber update` command or something like this 👍

**Comment by alexparker** [comment]
this seems like it might get complicated if you've made any mods to the microserver code. Or just run a diff/overwrite prompt the way `ember init` addresses this when updating ember versions on an existing codebase.

**Comment by Appsido** [comment]
or at least being able to delete a project because while testing with an account i got 5 projects named the same due to lumber generate same project multiple times

**Comment by SeyZ** [comment]
You're right guys! I'll try to improve this as soon as possible. Contributions are always welcome as well 😄

**Comment by alexparker** [comment]
Alex Parker

I'm interested in looking into creating a delete project method on the Authenticator that can be used by a delete command. 

a, pre, code, a:link, body { word-wrap: break-word !important; }

I haven't seen any tests. Am I missing them? Or just not written yet?

**Comment by SeyZ** [comment]
Hey @alexparker I didn't understand exactly what you want to do :(

**Comment by nzhenry** [comment]
@Appsido see https://github.com/ForestAdmin/lumber/issues/58

**Comment by SeyZ** [comment]
The `lumber update` command is now available.
