### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Oxicode** [ForestAdmin/lumber#38]
![image](https://cloud.githubusercontent.com/assets/1320709/20896100/2882a7f2-baea-11e6-9cfb-3c7bca52e75c.png)

**Comment by SeyZ** [comment]
Hey @Oxicode I think you're running an old version of Node.js right?
If you need to upgrade it. Feel free to reopen this issue if the problem still perists :)
