### ISSUE TITLE
Unprocessable Entity Error - No fix

### ISSUE THREAD

**Issue by divrse** [ForestAdmin/lumber#387]
## Expected behavior
Create app with mongodb 

## Actual behavior

TODO: Please describe here the behavior you are expecting.

Everytime I create a new project, I get an Unprocessable Entity issue.

So i made an app, and the first build worked, but i got the application host wrong so I needed to rebuild.

I delete the app, and start over

Now everytime I run the docker command I get Unprocessable Entity - which is a status code returned by your API.

I have no idea how to fix this and my only guess is that you're declining the creation of the app possibly by mongo url.

## Failure Logs

TODO: Please include any relevant log snippets, if necessary.

Error: Unprocessable Entity - create issue on github

* Lumber Package Version: Docker / latest
* Database Dialect: mongo
* Database Version: latest

**Comment by arnaudbesnier** [comment]
Hi @divrse 

I am afraid your issue report does not contain enough contextual information to let us start investigating your issue.

Does the issue persist? If so can you describe step by step what you did to encounter the issue.
We need a maximum of details 🙏 

I am also sorry to say that "Database Version: latest" is not an acceptable version.

Let us know once your issue description has been updated.

Thanks.
