### ISSUE TITLE
There is no package.json but installation success!

### ISSUE THREAD

**Issue by heinzin** [ForestAdmin/lumber#39]
cd forestadmin && npm install...
npm WARN enoent ENOENT: no such file or directory, open '/var/www/html/laravel/forestadmin/package.json'
npm WARN forestadmin No description
npm WARN forestadmin No repository field.
npm WARN forestadmin No README data
npm WARN forestadmin No license field.

👍  Hooray, installation success! 👍

Run your admin microservice:
$ cd "forestadmin" && node ./bin/www

**Comment by BrandonRomano** [comment]
I am also experiencing this issue:

```
brandon@brandons-mpb $ node --version
v6.9.1
brandon@brandons-mpb $ npm install -g lumber-cli
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/Users/brandon/.nvm/versions/node/v6.9.1/bin/lumber -> /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/lumber-cli/lumber.js
/Users/brandon/.nvm/versions/node/v6.9.1/lib
└── lumber-cli@1.2.3 

brandon@brandons-mpb $ lumber generate
ℹ︎  Enter your database connection details and then your admin interface will be automatically generated.
ℹ︎  Your database credentials are safe. They are only stored in the Lumber generated microservice.

? What's the database type?  postgres
? What's the database name? forest_example
? What's the database hostname? localhost
? What's the database port? 5432
? What's the database user?  brandon
? What's the database password? [optional]  ********
? Choose a project name:  forest_example

cd forest_example && npm install...
npm WARN enoent ENOENT: no such file or directory, open '/Users/brandon/Desktop/forest/forest_example/package.json'
npm WARN forest_example No description
npm WARN forest_example No repository field.
npm WARN forest_example No README data
npm WARN forest_example No license field.

👍  Hooray, installation success! 👍

Run your admin microservice:
$ cd "forest_example" && node ./bin/www

brandon@brandons-mpb $ cd "forest_example" && node ./bin/www
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/brandon/Desktop/forest/forest_example/bin/www'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
brandon@brandons-mpb $ ls 
etc/          node_modules/ 
```

**Comment by jaseemkp** [comment]
I got same issue.
``
╭─Jaseem@Jaseems-MacBook-Pro.local [Fri Jan 06, 10:58] ~/projects/Samples/lump
╰─➤  lumber generate
ℹ︎  Enter your database connection details and then your admin interface will be automatically generated.
ℹ︎  Your database credentials are safe. They are only stored in the Lumber generated microservice.

? What's the database type?  mysql
? What's the database name? lumb
? What's the database hostname? localhost
? What's the database port? 3306
? What's the database user?  root
? What's the database password? [optional]
? Choose a project name:  lumb-admin

cd lumb-admin && npm install...
npm WARN enoent ENOENT: no such file or directory, open '/Users/jaseem/Projects/Samples/lump/lumb-admin/package.json'
npm WARN lumb-admin No description
npm WARN lumb-admin No repository field.
npm WARN lumb-admin No README data
npm WARN lumb-admin No license field.

👍  Hooray, installation success! 👍

Run your admin microservice:
$ cd "lumb-admin" && node ./bin/www
``

**Comment by SeyZ** [comment]
Hey @jaseemkp @BrandonRomano @heinzin - In order to help me identifying more precisely the problem, can you tell me if you have a schema named `public` on your database?

**Comment by BrandonRomano** [comment]
@SeyZ -- Nope, it was an empty newly created database with no tables!

**Comment by SeyZ** [comment]
@BrandonRomano Oh I see. I will improve that, but Lumber needs to have tables available on your database to be able to create the project. Otherwise, your admin will be simply empty.

I will add a warning message to explain what's the error.

Same things for you @jaseemkp @heinzin ?

**Comment by SeyZ** [comment]
Please, reopen this issue if the problem is not just "an empty database" @jaseemkp @heinzin 

Thank you @BrandonRomano !
