### ISSUE TITLE
HasMany relationship. Mongoose

### ISSUE THREAD

**Issue by lomkovsky** [ForestAdmin/lumber#397]
## Expected behavior

Hello. I faced an issue. I have two collections. Products and Categories. Products references to Categories by link stored in Products collection “parent”. I create mongoose reference in my back-end connector. 

```
products.js
...
mongoose.Schema({
...
  'parent': { type: mongoose.Schema.Types.ObjectId, ref: 'productCategories' },
...
})
```

 This is how it gets displayed in forest admin: https://drive.google.com/open?id=1F1JNCq0JMJ-M863-fH6ZT8lJMkB0PsZq

## Actual behavior

Also, I have two another collections Workplaces and CraftsList 
Now, Workplaces connect to CraftsList as an array of references. 

```
workplaces.js
...
mongoose.Schema({
...
  'craftmanships': [{ type: mongoose.Schema.Types.ObjectId, ref: 'craftsList' }],
...
})
```
If I go the same way, it gets hidden from the table view and I see it only in "details" in the "RELATED DATA" section: 
https://drive.google.com/open?id=1pp4k7inrLxDscxBkACvW8nT1SHxPSNDd

Question: How can I make it viewable in table view and behave the same as for one reference field? I mean: “Reference field
When a workplace is referenced, I want to see the field…”

* Lumber Package Version: 6.13.4
* Liana Version: 5.7.0
* Database Dialect: MongoDB
* Database Version: 4.2

**Comment by arnaudbesnier** [comment]
Hi @lomkovsky,

You're describing Forest Admin default behavior here:
- single references are natively displayed in Table View
- array of references are not.

I am afraid you won't be able to do that so far.
I close this issue, feel free to re-open it if you need more information.

🌲🌲🌲
