### ISSUE TITLE
Project generation fails when schema is empty

### ISSUE THREAD

**Issue by emir-harbinja** [ForestAdmin/lumber#41]
The CLI project generation process will fail if the provided schema (currently hard coded to `public`) of the PostgreSQL database provided is empty.
A reasonable expectation would be to either that it successfully creates a fully fledged project with no models present, or that the CLI reports a meaningful error message to the user.

Because the CLI does not currently support providing a schema name as an argument, databases which do not store their tables inside the `public` schema cannot be used.

**Comment by SeyZ** [comment]
Already fixed
