### ISSUE TITLE
Support providing a schema name when generating a project

### ISSUE THREAD

**Issue by emir-harbinja** [ForestAdmin/lumber#42]
When generating a project, the user should be able to provide a schema name from which the tables will be read. 
This is especially useful for larger projects which heavily rely on schema as namespaces.

Please note that for PostgreSQL, the current version of Sequelize does not support providing a schema name to the `showAllTables` and `describeTable` methods of `QueryInterface` (there is a pull request for this [issue](https://github.com/sequelize/sequelize/pull/5515)).

**Comment by SeyZ** [comment]
Hey @emir-harbinja 

You're right, sequelize does not support "schema" option for `showAllTables` 😢 
I think I will need to patch this before solving the issue on Lumber.

**Comment by SeyZ** [comment]
@emir-harbinja It's now available on the version 1.3.0 👍
