### ISSUE TITLE
There is no images inside https://docs.forestadmin.com/documentation/reference-guide/models

### ISSUE THREAD

**Issue by pahaz** [ForestAdmin/lumber#433]
# Actual behavior
I'm trying to read the https://docs.forestadmin.com/documentation/reference-guide/models
![image](https://user-images.githubusercontent.com/1394025/82038137-c2344180-96ab-11ea-9dc6-9d7147ee559a.png)

**Comment by rap2hpoutre** [comment]
Thank you for the feedback! This has been fixed.
