### ISSUE TITLE
Any plans for mongo?

### ISSUE THREAD

**Issue by pajtai** [ForestAdmin/lumber#44]
This looks like a great tool. The docs say "Works with every stack." Do you have any plans for mongo compatibility in the future?

**Comment by SeyZ** [comment]
Hey @pajtai Yes, we're working on it :)

**Comment by codeHatcher** [comment]
I'm interested in the mongo variant, is it possible to keep this issue open until it is implemented so when it is closed I can check it out?

**Comment by SeyZ** [comment]
You're right @codeHatcher !

**Comment by alexpchin** [comment]
Looking forward to it!

**Comment by alexthewilde** [comment]
@SeyZ can you give a little update on progress here? Is this a matter of weeks or rather months?

**Comment by msabae** [comment]
@SeyZ yes please! Any idea when this could be rolled out? It would be great if you can give us some sort of ETA. Thanks a lot!

**Comment by cameronrll** [comment]
Would also be interested in a mongo version. If possible, like @msabae said, an ETA would be great

**Comment by gusgustavo** [comment]
Hey, updates about this?

**Comment by yanisIk** [comment]
Forest admin already works with Mongoose, so they already have the code ready, I think they just need to adapt it to the open source version of Forest.

I hope it will be soon, Lumber is really one essential piece missing in the Node.js world.

**Comment by VadimShvetsov** [comment]
It would be nice if we can use mongoose models without refactoring it with new types or other unnecessary syntax sugar.

**Comment by yanisIk** [comment]
Any news about that ?

**Comment by Nisthar** [comment]
any updates?

**Comment by SeyZ** [comment]
The simplest way to use Forest using a MongoDB database is to start from this working example: https://github.com/ForestAdmin/forest-examples/tree/master/examples/mongodb-database/simple
