### ISSUE TITLE
view codes does not work

### ISSUE THREAD

**Issue by perfectwebtech** [ForestAdmin/lumber#440]
hello

is it view code not work in production or development on self hosted solution ? 

must pay 250 usd for  database generated code success but view does not generated 

in app.forestadmin.com works fine but on my selfhosted solution does not apear view

but apear models and middleware offcourse 

anybody can help me ? how can done in community edition ?

**Comment by rap2hpoutre** [comment]
Hi @perfectwebtech! Sorry for the late answer. 

> is it view code not work in production or development on self hosted solution ?

Forest Admin does not provide a self-hosted solution. You could have a look here for more information: https://help.forestadmin.com/article/do-you-offer-a-self-hosted,-on-premise-version-of-forest/

> anybody can help me ? how can done in community edition ?

I'm not sure I understood your actual issue. it seems more related to Forest Admin than Lumber (which is a CLI tool for install a backend for Forest Admin). Maybe you could open an issue in our community Forum: https://community.forestadmin.com/

**Comment by rap2hpoutre** [comment]
Feel free to reopen this issue if required.
