### ISSUE TITLE
Stuck Connection to database

### ISSUE THREAD

**Issue by ardyfeb** [ForestAdmin/lumber#441]
## Failure Logs
```bash
$ lumber generate "<app-name>" --connection-url "<db-url> "ardyfeb@juabali.com" --token "<token>"
Connecting to your database
```

## Context
* Lumber Package Version: 3.6.0
* Database Dialect: pg
* Database Version: 10.6

**Comment by ardyfeb** [comment]
When runnng admin backend with docker with custom application host
```bash
✖ Creating your project on Forest Admin
> An unexpected error occurred. Please reach out for help in our Slack community or create a Github issue with following error: Error: Unprocessable Entity
```

**Comment by ardyfeb** [comment]
I do not want download and install ton of docker deps to my computer, so i run admin backend with gcp compute engine

**Comment by SteveBunlon** [comment]
Hello @ardyfeb 👋 

May I ask you to precise your version of NodeJS please ?

Steve.

**Comment by ardyfeb** [comment]
@SteveBunlon 

Node version is `v14.3.0`

**Comment by jean-tymate** [comment]
I tried with node `v12.18.2` and it worked.

**Comment by SteveBunlon** [comment]
Hello guys, we have released a fix for this one, I linked it to this thread.

Can you confirm it is working now please ?

**Comment by rap2hpoutre** [comment]
Hi @ardyfeb & @jean-tymate 👋 

You'll have to update lumber to the [latest version](https://github.com/ForestAdmin/lumber/releases/tag/v3.6.8) that includes the fix mentioned by @SteveBunlon. (3.6.1+)

```
npm install -g lumber-cli@latest
```

Since it should have been fixed, let me close the issue for now; feel free to re-open it if the problem persists.
