### ISSUE TITLE
PostgreSQL CITEXT columns not present in generated sequelize models

### ISSUE THREAD

**Issue by Tapppi** [ForestAdmin/lumber#47]
A lumber generated, postgresql connected admin will not have any CITEXT columns present in the generated sequelize models. The suspect function is [the `getType()` function](https://github.com/ForestAdmin/lumber/blob/master/services/table-analyzer.js#L28) in the table analyzer. Sequelize does not support CITEXT as a datatype according to their docs and I am unfamiliar with the framework, but it looks like you could just set CITEXT columns as Strings? 

I did find confirmation that someone is successfully [using CITEXT columns with sequelize](https://github.com/sequelize/sequelize/issues/6572).

**Comment by SeyZ** [comment]
You're right @Tapppi - STRING sequelize type works fine.
I'll fix that in the `getType()` function :)

**Comment by SeyZ** [comment]
Fixed by e8925f9813ba509c49a71241c0542da5420ff478
