### ISSUE TITLE
Cannot generate lumber project to my local database.

### ISSUE THREAD

**Issue by sayeko** [ForestAdmin/lumber#50]
As mention above I try to generate lumber microservice to my local mysql database that running under wamp bundle.
I get this error message:
error: Ouch, cannot connect to the database

I also set all my credentails perfectly.

**Comment by sayeko** [comment]
I figure out how to manage this problem but encounter another problem :(,

when running node ./bin/www

fatal exception unresolved name something like he trying to load any file.

**Comment by tranquochuy** [comment]
I think you have to use our Local address IP instead of localhost.

**Comment by sayeko** [comment]
I fixed it but encounter in another problem when I do this command cd folder && node ./bin/www

I get crash please help me figuerd it out.

**Comment by SeyZ** [comment]
Hey @sayeko 

What's the stacktrace please ?:)

**Comment by sayeko** [comment]
C:\Users\name last-name\Desktop\mainproject>cd "lumbertest" && node ./bin/www
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\name last-name\Desktop\mainproject\lumbertest\bin\www'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by sayeko** [comment]
Help?

**Comment by SeyZ** [comment]
Hey @sayeko Unfortunately I'm not on Windows and I can't reproduce your issue. Any help/contribution is more than welcome

**Comment by facundofarias** [comment]
I was able to fix it by running this: 
`npm install -g lumber-cli@latest`

Hope it helps.
