### ISSUE TITLE
Support for virtual fields

### ISSUE THREAD

**Issue by erenbali** [ForestAdmin/lumber#53]
I am defining a virtual type in my model definition.

```
{
  firstName: DataTypes.STRING,
  lastName: DataTypes.STRING,
  fullName: {
      type: DataTypes.VIRTUAL,
      allowNull: false,
      get: function () {
        return this.getDataValue('firstName')+' '+this.getDataValue('lastName');
      },
      set: function (fullName) {
        this.setDataValue('fullName', fullName);
      }
    },
}
```

The value appears in the API response and the field list where you customize the model. However, it doesn't appear on table view or detail view of the ForestAdmin page. You also can't make it the reference field.

**Comment by SeyZ** [comment]
Hey @erenbali You can create "virtual fields" using Smart Field. Here's the documentation: http://doc.forestadmin.com/developers-guide/?stack=express%2Fsequelize#smart-field

Feel free to reopen this issue if necessary.
