### ISSUE TITLE
golang api / docker compose / searchkit

### ISSUE THREAD

**Issue by roscopecoltran** [ForestAdmin/lumber#54]
Hi guys,

Hope you are all well !

I wanted to ask u 3 quick questions:

1. Do you have plan or know any golang based api for forestadmin ? if no, where can I find the list of all endpoints to create ? could not find any api doc online :-(

2. Is there any docker-compose template to boostrap quickly a local demo ? ([Laradock](https://github.com/LaraDock/laradock/) could be a good starting point ^^)

3. How complicated it would be to extend forestadmin/lumber with [searchkit](https://github.com/searchkit/searchkit) to use elasticsearch ?

Cheers,
Richard

**Comment by SeyZ** [comment]
Hello @roscopecoltran 

I'm doing very well, thank you :)

1. Lumber is completely framework-agnostic. It means the generated admin application is isolated from your customer-facing application in golang. We are based on the database, not the application. So yes, it should work :)

2. Good point! I would love to have a docker-compose with a demo database and a demo admin based on it just for testing. Contributions are more than welcome :)

3. Forest never access the data, it means Forest is not able to index the data to elastic search. The generated admin API supports advanced search/filters but not use elasticsearch. Is it a problem for you?

Feel free to reopen this issue if you still have questions :) Thank you @roscopecoltran !
