### ISSUE TITLE
Cannot load http://app.forestadmin.com/ in Chrome

### ISSUE THREAD

**Issue by justingosan** [ForestAdmin/lumber#55]
```
(index):18 Failed to find a valid digest in the 'integrity' attribute for resource 'http://app.forestadmin.com/assets/vendor-ec23afa0468d4ab8cab27a7d84c03371.css' with computed SHA-256 integrity 'f3o9dh3mAUmWIGcfnoosbSQI6SmLKXVLoWUMtr/oNHk='. The resource has been blocked.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://app.forestadmin.com/assets/client-dece4faf4c6a4991c9e672c9d15e3169.css' with computed SHA-256 integrity 'AwYDHDelTyFq8aknJZ9H1NcGXYArhUHoSGh1z+4l6hs='. The resource has been blocked.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://app.forestadmin.com/assets/client-ec0d1837b912b92dce8508beeed7082b.js' with computed SHA-256 integrity 'S0Yp9rgUN+hmbwGAXRzvWUvRCDBVWlY0I6L0NoqhC9o='. The resource has been blocked.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://app.forestadmin.com/babel.js' with computed SHA-256 integrity '/whk9HDJbofYvhlbAxbOWe7LBj43/wz0NKHCA3LpsEk='. The resource has been blocked.
```

I found a possible solution here https://github.com/ember-cli/ember-cli/issues/5040#issuecomment-154037707
...but i think it needs to be fixed on your end.

Thanks

**Comment by justingosan** [comment]
Ok I found that this only happens when you load via http:// not https://. You guys may want to update your link from the terminal to "https://"

![](https://dump-jz10.s3.amazonaws.com/monosnap/2017-01-10_13-14.png)

**Comment by SeyZ** [comment]
Hey @justingosan Thanks for your issue but I don't understand the issue. You're running your admin on localhost, so you don't have `https` right? Why it is not `http://app.forestadmin.com`? Can you help me to understand :) ?

**Comment by justingosan** [comment]
Hey @SeyZ, I wasn't really able to explore this product totally but form the brief trial that I did, you actually need to connect to their admin interface (where https://app.forestadmin.com points to) and access your local 'lumber' via an exposed api. Great product but In the end, it wasn't the solution I was looking for.

**Comment by SeyZ** [comment]
Hey @justingosan thank you! What's the pain you're trying to solve? :)

**Comment by justingosan** [comment]
I simply needed a generated admin interface hosted locally :)
