### ISSUE TITLE
Installation failing on windows 10

### ISSUE THREAD

**Issue by subodhpareek18** [ForestAdmin/lumber#57]
```
core-new $ lumber generate
ℹ︎  Enter your database connection details and then your admin interface will be automatically generated.
ℹ︎  Your database credentials are safe. They are only stored in the Lumber generated microservice.

? What's the database type?  postgres
? What's the database name? dvdrental
? What's the database hostname? localhost
? What's the database port? 5432
? What's the database user?  postgres
? What's the database password? [optional]  ********
? Choose a project name:  lumber

cd lumber && npm install...
npm ERR! addLocal Could not install D:\code\playground\core-new
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--prefix=lumber" "--progress=true"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\code\playground\core-new\npm-debug.log
�  Oops, NPM installation failed. Please, try it manually to have more info �
```

**Comment by zusamann** [comment]
Was able to continue by manually doing a `npm install` in the directory. So far it seems to be working fine.

**Comment by romainquellec** [comment]
I got exactly the same.

**Comment by SeyZ** [comment]
Thanks for report @zusamann and @romainquellec - Unfortunately I'm not on Windows 10 and it's hard for me to reproduce this issue. Contributions would be awesome :)

**Comment by zusamann** [comment]
hey @SeyZ what would you like me to do? I can record my screen and upload it here

**Comment by SeyZ** [comment]
A contributor on win10 would be the perfect solution

**Comment by pardus71** [comment]
i try it today and got also issues any solutions?

`
C:\Users\Anonymous\dev\a\i>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Anonymous\dev\a\i\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Anonymous\dev\a\i\package.json'
npm WARN i No description
npm WARN i No repository field.
npm WARN i No README data
npm WARN i No license field.

up to date in 0.128s

C:\Users\Anonymous\dev\a\i>npm start
npm ERR! path C:\Users\Anonymous\dev\a\i\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Anonymous\dev\a\i\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anonymous\AppData\Roaming\npm-cache\_logs\2018-02-18T02_17_09_688Z-debug.log

C:\Users\Anonymous\dev\a\i>`

**Comment by SeyZ** [comment]
`lumber generate` won't execute `npm install` at the end of the process anymore. With the latest versi on of Lumber, the instruction asks you to manually execute `npm install` in the generated folder.

Please, reopen this issue if the problem still exists.
