### ISSUE TITLE
Removing lumber old project

### ISSUE THREAD

**Issue by sayeko** [ForestAdmin/lumber#58]
Hi I have several project of lumber but I cant delete them there is no button or flag that I can click to remove them.

**Comment by cristianvaleri** [comment]
Also I need this feature

**Comment by eddiedsitt** [comment]
+1
major needed feature as i created a project a few times but only have one working project.

**Comment by SeyZ** [comment]
@sayeko @eddiedsitt @cristianvaleri you can now delete projects in the Forest Admin UI 👍
