### ISSUE TITLE
Oops, your database is empty.

### ISSUE THREAD

**Issue by jnmitch** [ForestAdmin/lumber#63]
After entering the prompts, Lumber returns "Oops, your database is empty. Please, create some tables before running Lumber generate." Isn't that what the 'lumber generate' script is supposed to do - create some tables? Of course a new database would be empty....waiting to be populated by the script.

So, I have tried "creat[ing] some tables before running Lumber generate" just to have something already in the database, but the script returns the same error. So with some useless tables added or without any, the script fails and returns this error. Why?

System: CentOS Linux 7.3.1611 on x86_64
Database: PostgreSQL 9.6.2
Lumber: 1.2.4

![lumber](https://cloud.githubusercontent.com/assets/15165195/23036989/03d13a5e-f442-11e6-8967-b7539690f73b.PNG)

**Comment by jnmitch** [comment]
Closing. Moved to a more robust and better maintained framework.

**Comment by Permpkin** [comment]
@jnmitch Is there currently a way to resolve this issue?

**Comment by jnmitch** [comment]
@Permpkin I don't know. I abandoned Lumber.
