### ISSUE TITLE
Lumber failed to deploy to heroku

### ISSUE THREAD

**Issue by MEKNI-D** [ForestAdmin/lumber#64]
When trying to deploy admin dashboard to heroku this message knowing that I logged into heroku but still getting this message. I also created an app on heroku and set up the environment variables, please help

"Ouch, you're not authenticated to Heroku yet. Please, run `heroku login` before."

**Comment by SeyZ** [comment]
@MEKNI-D What happens when you type `heroku login` and the error said?

**Comment by MEKNI-D** [comment]
It tells me that I am logged in as "my email" but when I try to type lumber heroku-deploy or lumber heroku-deploy-c I get a warning that indicates "Ouch, you're not authenticated to Heroku yet. Please, run heroku login before."

**Comment by KennethanCeyer** [comment]
I faced same error.

My command is follows.

```bash
$ pwd
> /my/admin/path

$ git status
> On branch master
> nothing to commit, working directory clean
# And the repository is hosted GitHub by private project.

$ heroku login
> Email: myemail@domain.com
> Password: ************
> Logged in as myemail@domain.com

$ lumber heroku-deploy -c
> Are you ready to push your admin on production?

> Requirements:
> - Your admin project needs to be hosted on GitHub (private repo recommended).
> - You must have a Heroku account (free) - https://signup.heroku.com
> - You must have Heroku CLI installed - https://devcenter.heroku.com/articles/heroku-command-line#download-and-install

> error: Ouch, you're not authenticated to Heroku yet. Please, run `heroku login` before.
```

OS: Windows 10.

lumber version: 1.2.9

heroku cli version: heroku-cli/5.9.2-2622131 (windows-amd64) go1.7.5

**Comment by SeyZ** [comment]
The logic behind `heroku deploy` was not smooth enough and we've decided to remove the command. Please use the instructions given by `lumber deploy` instead.
