### ISSUE TITLE
operator does not exist: integer = character varying

### ISSUE THREAD

**Issue by v-ken** [ForestAdmin/lumber#65]
DB: Postgres

Getting this error when accessing certain tables:
`operator does not exist: integer = character varying`

Quick google search gave me this:
http://stackoverflow.com/questions/23622993/postgresql-error-operator-does-not-exist-integer-character-varying

Looks like we're comparing an INT with a VARCHAR?

**Comment by SeyZ** [comment]
@v-ken I think it's related to your DB schema. I think you have a foreign key (VARCHAR) that points to a primary key (INT) or the opposite. Can you try to fix it? Reopen this issue if you think it's a lumber bug :)
