### ISSUE TITLE
lumber-cli generate doesn't accept connection-url flag

### ISSUE THREAD

**Issue by bosgood** [ForestAdmin/lumber#69]
Hi Forest,

Thanks for an awesome admin. I noticed the `lumber generate` command lists `--connection-url` as a [possible flag](https://github.com/ForestAdmin/lumber/blob/master/lumber-generate.js#L26), but I don't see any corresponding implementation to parse connection URLs.

Here's the output I get when providing that flag:

```
$ `yarn bin`/lumber generate --connection-url="postgres://lumber:password@localhost:5432/dev"
ℹ︎  Enter your database connection details and then your admin interface will be automatically generated.
ℹ︎  Your database credentials are safe. They are only stored in the Lumber generated microservice.

? What's the database type?  (Use arrow keys)
❯ postgres
  mysql
  mssql
```

It'd be awesome to have this (and other flags for every other interactive question) so that regenerating the app can easily be scripted. This would make it super simple to refresh models after a DB migration. Thoughts?

**Comment by SeyZ** [comment]
Hey @bosgood You're right, the --connection-url params is not parsed, this is a real issue.\

However, I'm not sure it is the best the way to handle DB migrations. The typical use case of Lumber is to scaffold the admin and then customize the models for missing relationships (e.g. hasMany), validations, and more.

I think Lumber needs to have a "Lumber migrate" that creates new models and fields and helps you merge conflicts.

**Comment by bosgood** [comment]
That sounds like a good plan too. As long as there is some way to work that model-generation magic again, that would work. Especially if it doesn't touch any other part of the generated app, since it's possible/likely that stuff gets customized post-generation.

Thanks for addressing this!

**Comment by SeyZ** [comment]
`lumber update` is now here for this :)
