### ISSUE TITLE
Express/Sequelize - Crashes on accessing smart field

### ISSUE THREAD

**Issue by sahilnarain** [ForestAdmin/lumber#71]
The Forest dashboard was set up using Lumber for Express/Sequelize.

I don't have any business logic integrated with the app right now, so I wrote a dummy function which returns static values.
```
'use strict';
var express = require('express');
var router = express.Router();
var liana = require('forest-express-sequelize');
var Serializer = require('forest-express').ResourceSerializer;

function topAppointments(req, res) {
  getAppointmentIds()
    .then((appointments) => {
      return new Serializer(liana, models.appointment, appointments, {}, {
        count: appointments.length
      }).perform();
      res.send(appointments);
    })
    .catch(next);
}

function getAppointmentIds() {
  var appointmentIds = [];
  for (var i = 0; i < 3; i++) {
    appointmentIds.push(parseInt(Math.random() * 100000));
  }

  return appointmentIds;
}

router.get('/forest/actor/:actorId/relationships/master', topAppointments);
```

Though the smart field is visible on the UI, clicking on the field crashes the server with the error -

*[forest] 🌳🌳🌳  record[("get" + _.capitalize(...))] is not a function*

**Comment by nickevansuk** [comment]
+1 please do include smart fields in the Lumber docs. I'm looking at calculated fields specifically.

**Comment by manurana** [comment]
this is the gist that will help replicate the issue : https://gist.github.com/manurana/5b6e54a21cebed8f0df13b2c010f06d0

**Comment by manurana** [comment]
This is what worked for us 
https://gist.github.com/manurana/da4dfec0ef1d7b532fa7e520e38c689f

Note that in the `router.get`, we don't need to add the `/forest` path, as it is implicit in the loading of the models.

**Comment by SeyZ** [comment]
Fixed 👍
