### ISSUE TITLE
Lumber doesnt like UUID

### ISSUE THREAD

**Issue by romainquellec** [ForestAdmin/lumber#72]
Hello ! 
The goal of this project is awesome. I was looking a admin-on-rest like, and Lumber seems to be the perfect solution.

I'm working on a new project and I'm using a lot of UUID's with postgresql. And lumber seems to hate that.

I got errors with relationships at the beginning so I commented it in two or three files in models.
After that, I launched the admin to get datas and got a lot of :

`
column "id" does not exist
column cuisine.id does not exist
operator does not exist: uuid = character varying
`

I'm pretty sure all these errors are related to uuids.

My not so long sql script : 

CREATE EXTENSION "uuid-ossp";

-- base on membership.db
DROP TABLE IF EXISTS user_account;
CREATE TABLE user_account (
  id                     uuid NOT NULL DEFAULT uuid_generate_v1mc(),
  email                  character varying(256),
  email_confirmed        boolean NOT NULL DEFAULT false,
  password_hash          character varying(100),
  security_stamp         character varying(100),
  concurrency_stamp      uuid NOT NULL DEFAULT uuid_generate_v1mc(),
  phone_number           character varying(50),
  phone_number_confirmed boolean NOT NULL DEFAULT false,
  two_factor_enabled     boolean NOT NULL DEFAULT false,
  lockout_end            timestamp without time zone,
  lockout_enabled        boolean NOT NULL DEFAULT false,
  access_failed_count    smallint NOT NULL DEFAULT 0,
  -- Keys
  CONSTRAINT user_account_pkey PRIMARY KEY (id),
  CONSTRAINT user_account_email_key UNIQUE (email)
);

DROP TABLE IF EXISTS user_login;
CREATE TABLE user_login (
  name      character varying(50),
  key       character varying(100),
  user_id   uuid NOT NULL,
  -- Keys
  CONSTRAINT user_login_pkey PRIMARY KEY (name, key),
  CONSTRAINT user_login_user_account_fkey FOREIGN KEY (user_id)
      REFERENCES user_account (id)
      ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS gourmet;
CREATE TABLE gourmet (
  gourmet_id   uuid NOT NULL,
  first_name   character varying(100),
  last_name    character varying(100),
  picture      json,
  gender       character varying(50),
  city         character varying(100),
  cp           character varying(10),
  description  text,
  created_at   timestamp without time zone DEFAULT timezone('utc'::text, now()),
  updated_at   timestamp without time zone DEFAULT timezone('utc'::text, now()),
  -- Keys
  CONSTRAINT gourmet_pkey PRIMARY KEY (gourmet_id),
  CONSTRAINT gourmet_user_account_fkey FOREIGN KEY (gourmet_id)
      REFERENCES user_account (id)
      ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS cuistot;
CREATE TABLE cuistot (
  cuistot_id   uuid NOT NULL,
  is_pro       boolean NOT NULL DEFAULT false,
  location     point NOT NULL,
  description  text,
  -- Keys
  CONSTRAINT cuistot_pkey PRIMARY KEY (cuistot_id),
  CONSTRAINT cuistot_gourmet_fkey FOREIGN KEY (cuistot_id)
      REFERENCES gourmet (gourmet_id)
      ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS cuisine;
CREATE TABLE cuisine (
  cuisine_id  uuid NOT NULL DEFAULT uuid_generate_v1mc(),
  name        character varying(100),
  location    point NOT NULL,
  CONSTRAINT cuisine_pkey PRIMARY KEY (cuisine_id)
);

DROP TABLE IF EXISTS atelier;
CREATE TABLE atelier (
  atelier_id        uuid NOT NULL DEFAULT uuid_generate_v1mc(),
  name              character varying(100),
  price             smallint NOT NULL,
  duration          smallint NOT NULL, --minutes
  max_gourmet       smallint NOT NULL,
  description       text,
  pictures          json,
  cuisine_id        uuid,
  cuistot_id        uuid NOT NULL,
  atelier_date      timestamp without time zone NOT NULL,
  CONSTRAINT atelier_pkey PRIMARY KEY (atelier_id),
  CONSTRAINT atelier_cuisine_fkey FOREIGN KEY (cuisine_id)
      REFERENCES cuisine (cuisine_id),
  CONSTRAINT atelier_cuistot_fkey FOREIGN KEY (cuistot_id)
      REFERENCES cuistot (cuistot_id)
);

DROP TABLE IF EXISTS reservation;
CREATE TABLE reservation (
  gourmet_id    uuid NOT NULL,
  atelier_id    uuid NOT NULL,
  amount        smallint NOT NULL DEFAULT 1,
  CONSTRAINT reservation_pkey PRIMARY KEY (gourmet_id, atelier_id),
  CONSTRAINT reservation_gourmet_id_fkey FOREIGN KEY (gourmet_id)
      REFERENCES gourmet (gourmet_id),
  CONSTRAINT reservation_atelier_id_fkey FOREIGN KEY (atelier_id)
      REFERENCES atelier (atelier_id)
);

I can investigate a bit. Tell me if you know a quick fix to that. Thank you.

**Comment by jamesone** [comment]
Any update on this?

**Comment by SeyZ** [comment]
Hey @jamesone @romainquellec let me try to reproduce this issue. I'll keep you updated!

**Comment by SeyZ** [comment]
feel free to reopen this issue if needed :)

**Comment by jamesone** [comment]
Thanks for fixing it so fast!! Will reopen if I see anymore issues

Sent from Outlook




On Wed, Apr 5, 2017 at 9:35 PM +1000, "Sandro Munda" <notifications@github.com> wrote:












feel free to reopen this issue if needed :)
