### ISSUE TITLE
How to deploy other than to heroku?

### ISSUE THREAD

**Issue by indrasantosa** [ForestAdmin/lumber#75]
Hey, as mentioned in the title, how to deploy other than to Heroku?
Thanks in advance!

**Comment by manurana** [comment]
##STEP1
If you have already created a github repo for your generated code, you can clone it on any machine.
```bash
git clone xxxx/lumber-admin
cd lumber-admin
npm install
```
##STEP 2
Create a new environment in your Forest admin UI, and copy its environment secret.

##STEP3
create a dotenv file in the lumber-admin dir in your new machine (copy the one in your local install), and replace the environment secret with the new one
```bash
vi .env
```
##STEP4
Hard refresh your UI. Now you should see that it has recognized your new environment

**Comment by SeyZ** [comment]
@indrasantosa you can now use the command `lumber deploy` 👍

**Comment by indrasantosa** [comment]
Thanks Sandro :)
