### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hamelsveld** [ForestAdmin/lumber#76]
💀  Oops, your database is empty. Please, create some tables before running Lumber generate.💀

This is what i get when trying to do a lumber generate....

Lumber version 1.2.9

is there a fix?

**Comment by SeyZ** [comment]
@hamelsveld I think your database is under a non-default schema (public on postgres). Lumber 1.3.0  supports other schema now. Can you try with the new version? Feel free to reopen this issue if needed.
