### ISSUE TITLE
Action restricted to a segment

### ISSUE THREAD

**Issue by balda** [ForestAdmin/lumber#83]
Is it possible to restrict an action to a model segment?

For example, `Users` model segmented in `active` users and `inactive` users.

```javascript
liana.collection('Users', {
    segments: [{
        name: 'Actives',
        where: {
            active: true
        }
    }, {
        name: 'Inactives',
        where: {
            active: false
        }
    }, ]
});
```

I want to add a `Make Active` action when `inactive` segment is selected. And `Make Inactive` when `active` segment is selected.

**Comment by arnaudbesnier** [comment]
hey @balda, you can restrict actions to a segment.
You just have to:

- create your segments in "Edit Layout" mode in the UI (http://doc.forestadmin.com/developers-guide/#creating-a-segment),
- then, declare your action (http://doc.forestadmin.com/developers-guide/#what-is-a-smart-action),
- once the action is accessible in the UI, you can restrict it to the segments you want in the settings of the related collection.

🌲🌲 🌲
