### ISSUE TITLE
Date fields (timestamps) ignored

### ISSUE THREAD

**Issue by schwarzh80** [ForestAdmin/lumber#84]
I have tried ForestAdmin first time today and I just realized that somehow all date fields are ignored from my database model. I use a MariaDB and have fields that are named "date_created", "date_updated" and "date_deleted" - all are TIMESTAMPS.

I have also tried a MySQL database with the same model and even there all date fields do not show up.

<img width="890" alt="bildschirmfoto 2017-06-09 um 15 53 04" src="https://user-images.githubusercontent.com/19378468/26978499-05879684-4d2c-11e7-8c3e-0d642f823ac1.png">
<img width="368" alt="bildschirmfoto 2017-06-09 um 15 53 16" src="https://user-images.githubusercontent.com/19378468/26978498-05842620-4d2c-11e7-8229-fbfa7e17a5c5.png">

Is there anything that I am doing wrong?
Thanks for your help!

Frank

**Comment by arnaudbesnier** [comment]
Hey @schwarzh80, thanks for the feedback.
The fix should be validated soon.
