### ISSUE TITLE
Empty returns

### ISSUE THREAD

**Issue by monteirobrena** [ForestAdmin/lumber#86]
Everything seems correctly configurated, no errors in log application but no results appear in the admin interface.

In web interface I've been receive this error:

```
client-3668bd0….js:18 [forest] 🌳🌳🌳 Unexpected error in the list view:  
n {isAdapterError: true, description: undefined, fileName: undefined, lineNumber: undefined, message: "The adapter operation was aborted"…}
```

There is my console output:
```
OPTIONS /forest/stats/users 200 8.500 ms - 2
POST /forest/stats/users - - ms - -
OPTIONS /forest/stats/users 200 0.361 ms - 2
```

**Comment by SeyZ** [comment]
Please, reopen this issue if the problem still exists on the latest version of Lumber
