### ISSUE TITLE
How add new view

### ISSUE THREAD

**Issue by lyudad** [ForestAdmin/lumber#93]
I cteated new Smart View, it is empty, where I should paste the code

![default](https://user-images.githubusercontent.com/25103090/27517474-25517352-59d6-11e7-95dc-541f9b0a5d35.PNG)

 if I want work with this view.  documentation have example only for action

**Comment by lyudad** [comment]
finaly find documentation http://doc.forestadmin.com/developers-guide

**Comment by arnaudbesnier** [comment]
So this is a closed issue right?
