### ISSUE TITLE
add roles problem

### ISSUE THREAD

**Issue by lyudad** [ForestAdmin/lumber#94]
How add new role to admin panel? or change permissions for exists one. for example show some table for user with role Admin and not show for role Editor

**Comment by arnaudbesnier** [comment]
Hi @lyudad,

Tables display configuration is based on Teams (not on Users Roles).
So if you want to have different configuration for different people, you have to create teams and then configure the layout for each of the team.

Finally, you will be able to invite teammates to the teams you want.

Hope it will help!

🌲🌲🌲

**Comment by lyudad** [comment]
I did'nt find how I can open some models to one team and other models to other team

**Comment by louisteenbrink** [comment]
Hey @lyudad 

In Forest, you can create different teams (go to your project settings -> Teams). 

You can configure the UI of each teams: hide/show collection, define collection in read-only mode or configure dashboards. See here [http://g.recordit.co/j6llYPvCWs.gif](url) how to hide/show collections.

Once you're done configuring the UI, you can invite your teammates in your different teams. Then, you can choose the role of your teammates (admin, editor or user) and they'll have only access to the UI your configured to them in their team :)

Let me know if that helps
